### ISSUE TITLE
Could not set artifact or see project list!

### ISSUE THREAD

**Issue by Moniarchy** [LearnersGuild/los#100]
### Expected vs. Actual

I was attempting to set an artifact, I got the message (Error:\* No such project exist with that name for that player).
Then I attempted to see what projects were on for this cycle. Got the message (There are 0 active projects this cycle. You have participated in 15 projects thus far.)
Then I attempted to list projects in review. There were none.
### Steps to Reproduce

The commands I typed were **/project set-artifact #acrid-zorro https://docs.google.com/document/d/1DJJ9Btkbjmwr6EP_UPK_X5UtNIR781tKQVfhkqVPyfk/edit?usp=sharing**, then **/project list**, then **/project list -r**
### Environment and Versions

Used echo on google chrome!

**Comment by jeffreywescott** [comment]
Thanks for this report! Sorry for the gruesome bug. It should be fixed now.
