### ISSUE TITLE
player stats

### ISSUE THREAD

**Issue by AbrahamFergie** [LearnersGuild/los#101]
### Expected vs. Actual

_What were you attempting to do? What actually happened?_
lookup stat updates, mine and Harman's stats because we were partnered last week and he didnt get to finish his retro on time.
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
no bug exactly just past retros were completed due to absence and now stats have not been recalculated
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_
nothing but the spreadsheet app used to display the stats opened on chrome browser

**Comment by jeffreywescott** [comment]
Hi, @AbrahamFergie ... I'm unclear on what you're asking for here. Can you clarify? We periodically re-run the stats computation from the "epoch" of the game, so ... if the stats didn't make it into the last spreadsheet, they will make it into the next one.

Or are you saying you need to request data change? If so, please do that here: https://github.com/LearnersGuild/los/projects/1

**Comment by AbrahamFergie** [comment]
Ok submitted an issue at the end of week 18 and the start of week 19 but it
shows my stat progress for week 18 as zero'd out across the board

**Comment by jeffreywescott** [comment]
Okay -- I've moved your issue here: https://github.com/LearnersGuild/los/projects/1

**Comment by bundacia** [comment]
@shereefb / @tannerwelsh: now that Harman is not here anymore, what's the best way to proceed here? I think this is a moderation decision.

**Comment by tannerwelsh** [comment]
@bundacia thanks. FYI, I'm not a moderator anymore :)

**Comment by shereefb** [comment]
retros that haven't been completed need to be "auto-closed" after some time has passed. 
Adding a new issue to track that.

**Comment by bundacia** [comment]
@shereefb, can you elaborate on what "closed" would mean so I can do in manually to this one?

**Comment by jeffreywescott** [comment]
Is there anything left to do here, or can we close this?

**Comment by jeffreywescott** [comment]
I'm closing this due to lack of response. Please reopen if further action is needed.
