### ISSUE TITLE
Distribute teams more evenly among pro players/OSS projects

### ISSUE THREAD

**Issue by jrobcodes** [LearnersGuild/los#107]
This is more feature request than bug report. :)

### Expected vs. Actual

Last week, 6 teams were originally assigned to lizardboard, 0 to floworky, and 1 to Trossello.  I am requesting that LOS/Game Moderators consider an addition to the algorithm to more evenly distribute players across OSS projects.

**Comment by bundacia** [comment]
Maybe goals need a "max teams" attribute in addition to a "team-size".

**Comment by jeffreywescott** [comment]
No longer relevant.
