### ISSUE TITLE
Break up ZPD across 3 health categories

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/los#108]
@arayi brought up that it's hard to estimate challenge/ZPD when there are different types of challenge (e.g. technical challenge vs. team play challenge).

So, instead of one ZPD number, measure challenge across all three dimensions of health: cultural, team play, and technical.

This way, learners can give log more fine-grained reflections on their challenge level at any given time.

Thanks for the insight @arayi!

**Comment by jeffreywescott** [comment]
@tannerwelsh / @shereefb: please close this once you've decided whether or not to integrate it.

**Comment by tannerwelsh** [comment]
Given that we no longer have the 3 health stats, going to close this for now.
