### ISSUE TITLE
Retrospective #delightful-darter (cycle 17)

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/los#109]
I gave this relative contribution 

@rachel-ftw 40%  
@deadlyicon 42%  
@EthanJStark 18%  

but I should have given this relative contribution 

@rachel-ftw 40%  
@deadlyicon 18%  
@EthanJStark 42%  

fix?

**Comment by jeffreywescott** [comment]
@deadlyicon  -- in light of our new support process, please use the #support channel in echo to get this resolved. We're trying to keep this repository for issues related to the software (bugs, feature requests, suggestions, etc.) rather than support / help requests. Thanks!

**Comment by bundacia** [comment]
done
