### ISSUE TITLE
Retro: clarity on which retro stats affect stats

### ISSUE THREAD

**Issue by EthanJStark** [LearnersGuild/los#110]
I only just now learned that the "higher resolution" bits on team play retro weren't affecting others' scores; perhaps that could be referenced while we take retro?

**Comment by jeffreywescott** [comment]
Hi, @EthanJStark -- would you please clarify what you mean? What are you suggesting, specifically? A change in the UI somewhere? Next to particular questions?

**Comment by jeffreywescott** [comment]
@EthanJStark -- because the team play stuff has been removed, I'm going to close this.
