### ISSUE TITLE
expose players and teams data

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/los#111]
Please expose the data for all players

- @handle 
- real name
- email address
- PGP
- avatar image url

as well as cycle teams

- team name
- member user ids

Please expose this via JSON somewhere so I ca build my own helpful tools.

**Comment by jeffreywescott** [comment]
@deadlyicon -- I gave you this API already, didn't I?

**Comment by jeffreywescott** [comment]
Closing -- no response.
