### ISSUE TITLE
Adding comments to project reviews

### ISSUE THREAD

**Issue by Moniarchy** [LearnersGuild/los#112]
Getting better at what we're doing culturally depends a lot on the written feedback we get from retros. We need a feature that allows us to write comments in project reviews too. If I continually get comments on my code that say that my variables are meaningfully named, that my functions are small and serve one purpose, or the like, I will make note of what I am doing well and continue to do those things. If I get feedback that tells me that I keep leaving comments in code, or that my files are too large, or any such things like that, I will also make note of those. 

Not sure if this way of phrasing makes sense, I can rephrase this if necessary.

**Comment by jeffreywescott** [comment]
Hi, @Moniarchy. This is an interesting suggestion! On the LOS team here at Learners Guild, we use GitHub Pull Requests and review process for leaving such feedback. Have you tried those tools? They're really well-developed, allowing you to comment on any line of any file. It seems unlikely that we'd want to duplicate that functionality in our systems. Unless I'm misunderstanding what you're asking.

**Comment by jeffreywescott** [comment]
@Moniarchy -- going to close this now that Review Accuracy and RXP are being rolled out: https://playbook.learnersguild.org/Game_Manual/Stats.html#project-review-stats
