### ISSUE TITLE
Back-fill missing retro data: Ana's pair from cycle 18

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/los#113]
In cycle 18, project `#ablaze-coot`, Ana worked with ? from outco. They were not around on Monday for retros/reviews, so we're missing data for the project and cannot calculate stats for Ana.

This can be resolved 1 of two ways:

1. We find out who the pair is, and have them submit a retro
1. We drop them from the project, and only use other retros
1. We make an educated guess as to how they'd respond and submit fake data

Obviously the first option is preferred.

**Comment by Anasauce** [comment]
Just to clarify, the cycle was week 17, my Out.co partner left mid-week so they never submitted a retro. I'm pretty sure my Out.co partner from week 18 did submit their retro (even though they weren't here) because I received written feedback from them in Echo. Also, I was never in the team #ablaze-coot...so maybe this is another learner?

**Comment by Anasauce** [comment]
![screen shot 2016-11-21 at 10 23 19 am](https://cloud.githubusercontent.com/assets/6962945/20495195/e69eed98-afd4-11e6-8fb0-32cf287d4460.png)

**Comment by Anasauce** [comment]
Those were my stats from that week...I actually don't know what (if any can/or needs to be changed). The only thing was that I got 0 Elo gain from that week...but that might just be the nature of the game at this point...thanks for looking into this :)

**Comment by jeffreywescott** [comment]
@tannerwelsh / @Anasauce -- in light of our new support process, please use the #support channel in echo to get this resolved. We're trying to keep this repository for issues related to the software (bugs, feature requests, suggestions, etc.) rather than support / help requests. Thanks!

**Comment by bundacia** [comment]
Closing this ticket as it doesn't seem like there are any manual data changes needed here.
