### ISSUE TITLE
Framing of free-response portion of retro

### ISSUE THREAD

**Issue by EthanJStark** [LearnersGuild/los#115]
When completing a retro, a player is prompted with something akin to: 

> I want to work with Person X because ____
> I would want to work with Person X more if ______

This prompt is asking for, as @needdra phrased it, an open-faced shit sandwich. 

Karim has offered excellent ways to frame feedback: 

- Actionable, Specific, and Kind
- Possibly: avoid giving advice. Instead, frame feedback in terms of "I experienced you doing action X. It had impact Y on me"

I think that it'd be very helpful to reframe this question to encourage higher-quality feedback.

**Comment by jeffreywescott** [comment]
@shereefb / @tannerwelsh: please close this once you've decided whether or not to integrate it.

**Comment by tannerwelsh** [comment]
Moved to clubhouse here: https://app.clubhouse.io/learnersguild/story/1398/reframe-free-response-question-in-retro. Thanks @EthanJStark!
