### ISSUE TITLE
Adjust my hours for week 16 and 17

### ISSUE THREAD

**Issue by yaseenagag** [LearnersGuild/los#116]
- kindly adjust week 17 hours from 25 to 20
- week 16 hours from 35 to 20
i missed days during those weeks and forgot to recalculate my hours

**Comment by jeffreywescott** [comment]
Hi, @yaseenagag  -- would you please send this request through our #support channel in echo? With our recent process changes, we're trying to use these issues as bug reports, feature requests, or suggestions for the software rather than for support / help. Thanks.

**Comment by bundacia** [comment]
Done. Hours for both those cycles changed to `20`.
