### ISSUE TITLE
Foundational Project Placement Issue

### ISSUE THREAD

**Issue by lizzkats** [LearnersGuild/los#118]
### Expected vs. Actual

I voted for two new practice projects and was placed on the same foundational project that I had last week, which was Database Fundamentals (tutorials on SQL)

### Steps to Reproduce

Not sure if it's a bug or not but it seems like a waste of time for someone to do a tutorial twice. 

### Environment and Versions

Google chrome, echo, El Capitan :)

**Comment by lumodon** [comment]
I agree that that project does indeed feel like a waste of time doing twice. On my second time I did it in 3 days (we had a short week and I used a day off) and just added content to a git-doc for others to use, but even then, it didn't at all feel productive.

**Comment by jeffreywescott** [comment]
Fair point. The algorithm that creates projects is definitely imperfect. I'm not sure how we can address this. Best suggestion at this point: if you get put on a project twice, ask a moderator if you can change the goal.
