### ISSUE TITLE
Review submission for invalid project (typo) results in unhelpful error message being displayed

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/los#12]
### Expected vs. Actual

**Expected:**
Expected an error message indicating that the project could not be found / was invalid.

**Actual:**
`Error:* Failed to save responses. Try`--help`for usage.`
### Steps to Reproduce

Submit a review that is valid in every way _except_ for the project name:

`/review misspelled-project -c 70 -q 70`
### Environment and Versions

Irrelevant.

**Comment by jeffreywescott** [comment]
Will be addressed by https://github.com/LearnersGuild/game/pull/239

**Comment by jeffreywescott** [comment]
Fixed.
