### ISSUE TITLE
Retros #equable-blesbok

### ISSUE THREAD

**Issue by mantinone** [LearnersGuild/los#120]
### Expected vs. Actual
I rated Aileen's technical health at Somewhat Agree last week.  After calculating the actual percentage score, I would like it raised to Agree.

**Comment by jeffreywescott** [comment]
Hi, @mantinone   -- would you please send this request through our #support channel in echo? We're trying to use these issues as bug reports, feature requests, or suggestions for the software rather than for support / help. Thanks.

**Comment by bundacia** [comment]
Done.
