### ISSUE TITLE
Pro players contribution to OSS projects not accurate

### ISSUE THREAD

**Issue by nodatall** [LearnersGuild/los#123]
Pro players don't know enough about team dynamics to make accurate assessments of contribution, especially when they have multiple teams. 

I think it would be better if their contribution estimations were removed from the equation.

**Comment by jeffreywescott** [comment]
Thanks for the suggestion, @nodatall.

**Comment by jeffreywescott** [comment]
@shereefb / @tannerwelsh -- would you please close this once you've decided whether or not to integrate this feedback into the mechanics?

**Comment by tannerwelsh** [comment]
This would be solved by https://app.clubhouse.io/learnersguild/story/47/players-can-choose-not-to-answer-relative-contribution-questions-in-retrospectives. Tracking in clubhouse, going to close here. Thanks @nodatall!
