### ISSUE TITLE
Need late Jrob retro data

### ISSUE THREAD

**Issue by EthanJStark** [LearnersGuild/los#124]
This cycle, our team, #callous-teal, which includes Moniarchy and jrob8577, 
@jrob8577 was unable to complete his Retro before the cycle closed (as he's on vacation). Noting this here, so that his retro data can be included retroactively.  Thanks, all!

**Comment by jeffreywescott** [comment]
Hi, @EthanJStark  -- would you please send this request through our #support channel in echo? We're trying to use these issues as bug reports, feature requests, or suggestions for the software rather than for support / help. Thanks.

**Comment by bundacia** [comment]
@jrob8577, you should now have the ability to complete uncompleted retros from previous cycles (we just deployed that change today). If you issue the `/retro` command in Echo you should get a list of all uncompleted retro's and be able to complete them.

**Comment by jrobcodes** [comment]
@bundacia To be sure I understand: is there something I need to do here? I think I was removed from the team since I was only here for a day that week...

**Comment by bundacia** [comment]
Oh ok. If you were removed from the project (I double-checked, you were) than nothing needs to be done here.

**Comment by jrobcodes** [comment]
Thanks!!
