### ISSUE TITLE
Oauth permissions are too strict

### ISSUE THREAD

**Issue by punitrathore** [LearnersGuild/los#125]
### Expected vs. Actual
Expected: Basic profile + email access 

Actual: When trying to authorize the Echo app with my Github account, it requests access to all private repos, as well as Organization access, which is excessive IMHO.

### Screenshot
<img width="815" alt="screen shot 2016-11-29 at 3 00 31 pm" src="https://cloud.githubusercontent.com/assets/96797/20732722/e07cd33c-b644-11e6-9497-bfa124ad53bf.png">

**Comment by jeffreywescott** [comment]
Tracked here: https://app.clubhouse.io/learnersguild/story/2095/oauth-permissions-are-too-strict
