### ISSUE TITLE
Emoji's are broken

### ISSUE THREAD

**Issue by mKleinCreative** [LearnersGuild/los#126]
### Expected vs. Actual

Emoji
### Steps to Reproduce

![screen shot 2016-12-01 at 8 43 17 am](https://cloud.githubusercontent.com/assets/1609748/20802872/4c1561d2-b7a2-11e6-90da-75f56298c81d.png)

### Environment and Versions

Echo Browser version, it looks like it isn't referencing the sheet of emoji's correctly? It's not only for me posting them, it's also bugged out on existing posts.

**Comment by bundacia** [comment]
@mKleinCreative I had the same thing happen to me. It's caching issue I believe. (Is it broken if you use a different browser?) Try clearing your browser cache. That fixed it for me.

**Comment by heyheyjp** [comment]
Thanks @mKleinCreative. Closing for now. Let us know if clearing the cache doesn't resolve it for you.
