### ISSUE TITLE
Adjust my hours for week 20

### ISSUE THREAD

**Issue by HJBowers** [LearnersGuild/los#128]
Please adjust my week 20 hours from 38 to 32.
I miss calculated my billable hours. Thank you!

**Comment by jeffreywescott** [comment]
Hi, @HJBowers -- would you please send this request through our #support channel in echo? We're trying to use these issues as bug reports, feature requests, or suggestions for the software rather than for support / help. Thanks.

**Comment by HJBowers** [comment]
I noticed this was reopened after you asked me to make my request through
the #support channel in echo. Do you still want me to post in echo?

Hannah

**Comment by jeffreywescott** [comment]
@HJBowers -- sorry -- we are working on the best process for this. Don't worry about reporting it for now.

**Comment by bundacia** [comment]
Done. Updated reported hours for @HJBowers on project `#ancient-kite` from `38` to `32`. Note that this was cycle 21, not 20.
