### ISSUE TITLE
Review scales feel too big

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/los#13]
### Expected vs. Actual

Expected: Something more reasonable. i don't need to be able to specify completeness and quality on a 100-point scale and am not sure I ever could with any sense of confidence in the accuracy and meaningfulness of the rating.

Actual: 100-point scales.

<img width="933" alt="screen shot 2016-07-01 at 2 04 39 pm" src="https://cloud.githubusercontent.com/assets/1890882/16534503/0d7aee68-3f95-11e6-9267-c2845a476f88.png">
### Steps to Reproduce

`/review --help`
### Environment and Versions

Irrelevant.

**Comment by jeffreywescott** [comment]
Passed onto UX team for consideration.
