### ISSUE TITLE
Channel list sometimes does not display

### ISSUE THREAD

**Issue by arayi** [LearnersGuild/los#130]
### Expected vs. Actual

During normal use, Echo occasionally stops displaying the channel list (still displays favorites).

### Steps to Reproduce

Does not appear to be correlated with any specific idle condition. Occurs in both browser and Mac client.

### Environment and Versions

Chrome Version 54.0.2840.98 (64-bit), OSX Version 10.11.6, browser-based Echo

**Comment by heyheyjp** [comment]
@arayi: please attach a screenshot if you have one/next time this occurs. Thanks!

**Comment by jeffreywescott** [comment]
We just merged-in the latest version of Rocket.Chat that hopefully fixes this. Please re-open (with a screenshot) if you see this again.
