### ISSUE TITLE
Survey Problem - Submitted Wrong Retro Information

### ISSUE THREAD

**Issue by TheLady** [LearnersGuild/los#132]
### Expected vs. Actual

_What were you attempting to do? What actually happened?_
I expected to give a favorable rating for Eugene Baah on Truth but somehow ended up giving him a zero.

### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
I can't necessarily reproduce the bug, but I do know that accidentally brushing across the wrong spot while scrolling down the Retro can change the selections. It's possible that that is what happened. Is there a way that I can look at the week 1 Retro I submitted for Eugene Baah? I really don't believe 0 accurately reflects what I meant to answer, and I feel horrible that he thought I did. I'm also concerned that other answers might have been other than what I intended. Thank you in advance for helping me look into this! Candida (Di) Haynes

### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_ Probably Safari 9.1.

**Comment by bundacia** [comment]
@TheLady, I've re-opened your survey. You can now change your responses with the `/retro` command.
