### ISSUE TITLE
Search all channels

### ISSUE THREAD

**Issue by jason00111** [LearnersGuild/los#133]
A search all feature that lets you search in all your channels.  Sometimes I remember reading something but I don't remember which channel it was in.

**Comment by jeffreywescott** [comment]
Try this:

<img width="1276" alt="rocket_chat_" src="https://cloud.githubusercontent.com/assets/130597/21194049/58a7c02a-c1e3-11e6-87f1-5f32a0102f97.png">

**Comment by jason00111** [comment]
This searches within a channel.
I'm suggesting a global search to search all channels at once.
