### ISSUE TITLE
Echo not saving my profile photo

### ISSUE THREAD

**Issue by TheLady** [LearnersGuild/los#134]
### Expected vs. Actual

_What were you attempting to do? What actually happened?_
I've uploaded my photo a few times, but it disappears the next day.

### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
I reproduced the bug by uploading a photo last night and logging in this morning. There was no picture :-(.

### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_Safari 9.1

This is obviously not an emergency, but thanks in advance for looking into it!

Candida Haynes (Di)

**Comment by jeffreywescott** [comment]
Hi, @TheLady ... if you change your profile photo on GitHub, it will automatically by synchronized into echo the next time you sign-out and sign-in again. Sorry for the confusion!

**Comment by TheLady** [comment]
Ahhh... thank you!
