### ISSUE TITLE
Change stats submitted week of the 28th

### ISSUE THREAD

**Issue by breyana** [LearnersGuild/los#135]
### Expected vs. Actual

I expected that putting Not Enough Information would skip the question, but it gave 0s. I'd like to re-enter the survey I filled out so that I can provide accurate stats

**Comment by bundacia** [comment]
@breyana, can you provide the name of the project team you were working on that week?

**Comment by breyana** [comment]
#ancient-kite

**Comment by bundacia** [comment]
@breyana, I've re-opened that survey for you, so you should be able to access it with the `/retro` command in Echo and resubmit answers. Let me know if you have any problems.
