### ISSUE TITLE
Wrong team. Can't do retro 

### ISSUE THREAD

**Issue by SalSoloman** [LearnersGuild/los#136]
### Expected vs. Actual

Due to my sickness, I've missed Monday and couldn't vote for a project, I was automatically paired with @teqnickels but found out when I came on Tuesday that she joined another team as a third member so I decided to join them too as a fourth member, but I found out when I was trying to do retro that am on the wrong team. 
Am suppose to be on team #merciful-eland but am currently in group #flimsy-buffalo

**Comment by heyheyjp** [comment]
Thanks, @SalSoloman. Looking into it.

**Comment by heyheyjp** [comment]
Should be all set.
