### ISSUE TITLE
@Thamaranth retro for week 23

### ISSUE THREAD

**Issue by thamaranth** [LearnersGuild/los#137]
I didn't get a chance to submit my retro for Cycle 23 because my child was born that weekend. How should I format the data to submit here?

**Comment by thamaranth** [comment]
contribution: Monica 45%
Najee 45%
Jrob 10%

hours : 32 hours

**Comment by bundacia** [comment]
@thamaranth, you should now have the ability to complete uncompleted retros from previous cycles (we just deployed that change today). If you issue the `/retro` command in Echo you should get a list of all uncompleted retro's and be able to complete them.
