### ISSUE TITLE
Changed stats of teammate have not updated my stats on the spreadsheet

### ISSUE THREAD

**Issue by sdweber422** [LearnersGuild/los#138]
Hello,

My stats do not seem to reflect changes that happened for the team that I was on week#21. My team was called #maddening-bandicoot. My ELO, my contribution bias, and my estimation bias are still not reflective of changes I was told to have happened during week 22. Carla DM'd me with my new ELO and my ELO on the stat sheet did not reflect this. Thank you.

Stephan Weber

**Comment by bundacia** [comment]
@tannerwelsh, do you update the sheet for past cycles when things change or just the tab for the current cycle?

**Comment by tannerwelsh** [comment]
Just the current sheet. Unfortunately previous sheets are stale as soon as they are created.

**Comment by bundacia** [comment]
@sdweber422, would that explain what you're seeing? Does the most recent tab look right to you? We're working on a better interface for stats that would show you all previous cycles and stay up-to-date in real time.

**Comment by jeffreywescott** [comment]
@sdweber422 now that we have the stats UI, can we close this issue?

**Comment by jeffreywescott** [comment]
Closing this due to lack of response. Please reopen if further action is needed.
