### ISSUE TITLE
please verify "technical health" average for @jhallman5

### ISSUE THREAD

**Issue by arayi** [LearnersGuild/los#139]
Wordsmithing from @arayi:

> A specific example brought to me by another learner is that @jhallman5 received 100%/strongly agree on his technical score for last week, yet reported that his overall _average_ score went down in the spreadsheet.

**Comment by jeffreywescott** [comment]
Hi, @arayi. Unfortunately, as it is written, this issue is not addressable.

Please update your report to include _specific_ inconsistencies that you are seeing. Without them, there's simply no action we can take to even look at this issue.

**Comment by arayi** [comment]
Output is consistently lower than expected based on the concept that each stat is just an average of the past six weeks. Is that not a specific enough inconsistency?

A specific example brought to me by another learner is that @jhallman5 received 100%/strongly agree on his technical score for last week, yet reported that score went down.

I have had multiple experiences similar to that. I'd have to thoroughly review the spreadsheet to give you a map of specific examples of inconsistencies - I'll do that when I have the ability to timebox it into my schedule.

Also relevant is that I currently have retros that are screwed up - I was moved off calm-alligator that week and should not be on that project, Jared has not submitted retros for last week (petite-kongoni), and I just haven't personally submitted my retro for disturbed-grison yet - but since a November learner is experiencing the same thing and tells me he has no missing retros, this bug appears to be independent of (though possibly worsened by) missing retros.

**Comment by arayi** [comment]
Would it be possible to take names out of the LOS repo and have them be part of the production environment instead? I am not the only learner who would be very appreciative of the ability to review the LOS code.

**Comment by jeffreywescott** [comment]
Thanks for the further detail, @arayi. I'm going to change this issue into a "data" issue and have someone investigate the averages for the technical scores for @jhallman5. That should be enough for us to report back.

**Comment by bundacia** [comment]
@arayi: after looking at the data in the spreadsheet the average technical health stats for @jhallman5 seem to match up with the ratings they received each cycle (I looked specifically at cycles 21-24). I can't share specific stats here without @jhallman5's permission, but if they have any further concerns they can reach out directly.

I'm going to go ahead and close this issue for now, but if you have any other examples of things that look off feel free to re-open it or create a new one.
