### ISSUE TITLE
Project names are cumbersome to remember and to type

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/los#14]
### Expected vs. Actual

Expected: Project names easy to type (or some help in typing them like autocomplete).

Actual: Project names like `exasperated-oystercatcher` that just feel like typo and frustration traps.
### Steps to Reproduce

Launch a cycle.
### Environment and Versions

Irrelevant.

**Comment by bundacia** [comment]
Project names will tab-complete if you prefix them with a `#`. The commands that accept project name parameters accept them with or without that prefix, so one way to mitigate this would be to show the `#` in the command examples so people know they can type it that way. It's not perfect but it's a cheap way to get a little improvement.

![woxat861mo](https://cloud.githubusercontent.com/assets/189699/16587772/71295d72-4289-11e6-9262-0094d50bf129.gif)

**Comment by jeffreywescott** [comment]
In light of @bundacia's comment, closing for now.

**Comment by heyheyjp** [comment]
@jeffreywescott: not sure this has been fully addressed. @bundacia's workaround is GTK (now) but isn't intuitive. If we won't at least update echo to include this tip, can we put this issue someplace else so that we don't lose sight of it?

**Comment by jeffreywescott** [comment]
I'm not sure I agree, @prattsj.The help text for the command implies that you should type a `#` when specifying project name. And if you do so, you get a drop-down with matching channel names. I'm not sure CLIs are ever "intuitive", though I do believe they should be consistent and should behave in a way that is "familiar" to other CLIs.

Remember -- we're building an interface for developers ... people who should be able to eventually become familiar with command-line interfaces, auto-complete, etc. I'm very reluctant to do too much hand-holding in the CLI. Maybe I'm misunderstanding what you mean by a "tip"?
