### ISSUE TITLE
Adjust my contribution for week 23

### ISSUE THREAD

**Issue by jason00111** [LearnersGuild/los#141]
JRob made a mistake while estimating contribution and my team assessed contribution was too low as a result.  He mixed up all the 'J' names and estimated his contribution as ~45 instead of a smaller number.

**Comment by bundacia** [comment]
@jrob8577 can you provide the team name, cycle number, and what your responses should have been?

**Comment by jason00111** [comment]
@bundacia @jrob8577 The team name was wonderful-hartebeest and it was cycle 22

**Comment by jason00111** [comment]
This error has been affecting my stats and possibly my level for weeks now.  Can someone fix it please? 😁

**Comment by jrobcodes** [comment]
I don't remember the team name or cycle number or what my responses should have been at this point.  Just remove me from the group?

**Comment by bundacia** [comment]
@jason00111: you were on a team with @jrob8577 for cycle 23 ([wonderful-hartebeest](http://game.learnersguild.org/projects/wonderful-hartebeest)) and cycle 22 ([dependent-potoroo](http://game.learnersguild.org/projects/dependent-potoroo)). Can you confirm that you're talking about wonderful-hartebeest? Just want to make sure I don't delete the wrong responses.

**Comment by bundacia** [comment]
Ok, I've removed @jrob8577 from wonderful-hartebeest along with all of his responses and all of the rest of the team's responses about him. Any relative contribution attributed to @jrob8577 by his teammates has been split evenly between the remaining team members. Stats have been recalculated.

**Comment by jason00111** [comment]
Thanks!
