### ISSUE TITLE
Stats weren't updated after retros were submitted

### ISSUE THREAD

**Issue by teqnickels** [LearnersGuild/los#142]
### Expected vs. Actual

Stats weren't updated after retros were submitted

### Steps to Reproduce
Multiple submissions of retros from 4 different team members, unsure of which ones stuck

### Environment and Versions

chrome

**Comment by bundacia** [comment]
@teqnickels, which stats are you looking at specifically? Which cycle? Are they still not updated?

**Comment by jeffreywescott** [comment]
@teqnickels -- are you still having an issue with your stats? Can we close this issue now that the stats UI is available?

**Comment by jeffreywescott** [comment]
Closing this due to lack of response. Please reopen if further action is needed.
