### ISSUE TITLE
Custom & private echo avatars

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/los#147]
We need everyone in echo to have an accurate image of their face. This raises privacy concerns for some players. Please allow for Custom & private echo avatars

**Comment by jeffreywescott** [comment]
So, for now (for unrelated reasons), echo (Rocket.Chat) is no longer synchronizing GitHub avatars. 

Leaving this issue open, however, so we can track the feature of adding  avatars to people's profile.
