### ISSUE TITLE
Oddly Worded Log Question

### ISSUE THREAD

**Issue by jrobcodes** [LearnersGuild/los#15]
### Expected vs. Actual

When completing the retrospective via the `/log` command, the wording of one of the evaluation questions was odd:

```
Q5*: Give feedback to your teammate by completing the following sentence:

"@jrob8577, I want to work with you because..."
```

Since I'm jrob, I'm not sure how to effectively answer this question.

**Comment by jeffreywescott** [comment]
Closing since these questions no longer appear. Once https://github.com/LearnersGuild/game/issues/281 is complete, we will have questions related to reflecting on "self".
