### ISSUE TITLE
Close retro for @compsight and @starrpatty28

### ISSUE THREAD

**Issue by shereefb** [LearnersGuild/los#151]
Is there anyway that stats can be run for @compsight and @starrpatty28 from last week. Our partner @sn0wp did not get to do a retro before she was locked out of echo (due to leaving the program)

**Comment by heyheyjp** [comment]
@shereefb: We can run stats for this project, sure. Are you also asking for the spreadsheet to be regenerated for cycle 25?

**Comment by jeffreywescott** [comment]
Is anything more needed here?

**Comment by jeffreywescott** [comment]
Closing this due to lack of response. Please reopen if further action is needed.
