### ISSUE TITLE
Echo downtime

### ISSUE THREAD

**Issue by jason00111** [LearnersGuild/los#152]
Echo is down a lot.  Can the developers use a test site or something instead of working on the live site?  Surely it is not best practice to work on the live site.

**Comment by heyheyjp** [comment]
The LOS development team doesn't do testing in the live/production environment. The underlying software for Echo (Rocket.chat) is simply unstable, and issues with image storage are causing the outages. Work to resolve these issues is underway.

**Comment by jeffreywescott** [comment]
Hey, @jason00111. Sorry Echo has been so unstable; we're well aware of it. I can assure you that it has absolutely nothing to do with the way we're working, but instead is [a bug with the underlying MongoDB GridFS integration](https://github.com/RocketChat/Rocket.Chat/issues/3929).

We are looking at ways to isolate ourselves from the bug, and I'll try to keep this issue updated if and as we make progress. Thanks for the feedback.

**Comment by jason00111** [comment]
Thanks for the clarification.  I shouldn't have assumed the reason for the downtime.  Thanks for your work.  A lot of us are relying on echo.

**Comment by jeffreywescott** [comment]
**UPDATE:** Becauase the main usage of GridFS in Rocket.Chat is for storing avatars, we've (a) disabled GridFS for avatars, and (b) stopped automatically updating people's avatars with their GitHub avatar. What this means is that avatars are stored on the filesystem (which is ephemeral between redeploys of echo), so folks will have to re-update their avatar periodically within Rocket.Chat itself. It also means that the avatars shown in other parts of the LOS (like the voting panel) will not necessarily be the same as the avatars in Rocket.Chat. While this is annoying, it's better than a crashing system. And it _does_ seem a bit more stable. Fingers crossed.

**Comment by heyheyjp** [comment]
This issue seems resolved by @jeffreywescott's latest changes. Closing.

**Comment by engelgabriel** [comment]
@jeffreywescott 
Are you using docker? 
Why don't you make the /upload a mount point to the node do the files are not ephemeral?

**Comment by jeffreywescott** [comment]
Thanks for the suggestion, @engelgabriel. Migrating everything to Docker is on our radar, but not currently a high priority.
