### ISSUE TITLE
It isn't clear that the player's name is clickable on game.learnersguild.org

### ISSUE THREAD

**Issue by breyana** [LearnersGuild/los#154]
## Expected vs. Actual

Visited https://game.learnersguild.org/users and saw a list of names that showed only ELO and XP stats.

The formatting does not give clarity that the names can be clicked to lead to a more detailed page

### Steps to Reproduce

1. Visit https://game.learnersguild.org/users
2. View the list of names

Result: 
There is no visual indication that the lines can be clicked

**Comment by jeffreywescott** [comment]
Thanks for this report -- we've pulled this into our Kanban board to prioritize.
