### ISSUE TITLE
Bug collection: Stats and levels

### ISSUE THREAD

**Issue by arayi** [LearnersGuild/los#156]
Experience: Does not reflect any objective measure having to do with growth. Suggest replacement with a tracking system for individual competencies, technical and non-technical.

Health stats: Should be directly actionable feedback about the individual's progress in these three areas. Instead is metadata about how well the team communicated around those stats. Should be a +/- vector based on how well the individual is meeting goals related to that particular stat, making these directly quantitative instead of qualitative. This will also help eliminate communication-style bias on teams that encounter difficulties in that area.

Levels: Are not progressive for every learner. For example, in my case, coaching or working directly with professional engineers (currently L3+) would be an appropriate "level one" difficulty project, while working as a teammate (rather than a PM) on an open source project would be the highest difficulty level because of the incredible amount of communication logistics involved (e.g., when multiple teams did not know they were working on the same feature because it was duplicated in the issue queue).

While I can address some of these things through an ADA request, I think it speaks to a larger set of bugs in the LOS.

Many learners feel like they are not getting the chance to appropriately target deficits. We are creating complicated social support structures around this when we could more easily address it within the structure of the game itself.

If we implement these changes, it will have vast benefits to the guild, including easing the anxiety and energy expenditure of learners and lessening the staff's workload, especially around stats coaching.

I have many specific suggestions regarding how to achieve this end (i.e. I could likely whiteboard a full outline, minus a few mathematical details, off the top of my head), but I am hesitant to spend the time detailing it here prior to a staff response because of how my suggestions have been received in the past.

Am I making a correct assumption that these things would be strongly in alignment with the guild's mission?

**Comment by shereefb** [comment]
> but I am hesitant to spend the time detailing it here prior to a staff response because of how my suggestions have been received in the past.

This comment is out of line. And does not belong in a technical issue.

> Many learners feel like they are not getting the chance to appropriately target deficits.

Please only speak for others if you've taken permission from them to speak on their behalf. Otherwise, only speak for yourself. Learners are perfectly capable of speaking for themselves and don't need you to do it for them. 

Feel free to re-file this when you have something more organized, specific, actionable and kind.

Closing as not actionable.
