### ISSUE TITLE
stats eval

### ISSUE THREAD

**Issue by AbrahamFergie** [LearnersGuild/los#158]
### Expected vs. Actual
<img width="1285" alt="screen shot 2017-01-30 at 10 23 00 am" src="https://cloud.githubusercontent.com/assets/15825329/22435801/56515878-e6d6-11e6-9369-4f8573a47dc3.png">

my partner had an elo of:  1000
my elo is: 975
if this could get looked at more closely, I wasn't sure if i got as much of a boost to my elo as i thought i should have gotten.

_What were you attempting to do? What actually happened? Please provide your project name and/or the cycle number if applicable._

### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._

### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
I asked @AbrahamFergie to file this. Should his elo change only be 2 in this case? I found it surprising. /cc @shereefb

**Comment by jeffreywescott** [comment]
bump @shereefb @tannerwelsh

**Comment by shereefb** [comment]
lgtm

Use this calculator, use a k-factor of 20, a draw = 1 point, this was slightly better than a draw so 2 points
http://www.3dkingdoms.com/chess/elo.htm
