### ISSUE TITLE
Confused about team name - I don't know where to find my individual team name

### ISSUE THREAD

**Issue by TheLady** [LearnersGuild/los#160]
### Expected vs. Actual

_I was trying to find my own team name so I could name my Github branch consistently. I only see a team (melted-springhare) with my name and Sal's so I am not sure I should use that name. The project name is Benchmark.

### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

I am using Chrome on a Mac El Capitain

### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._

**Comment by jeffreywescott** [comment]
As far as I can tell, [you are solo on this project](https://game.learnersguild.org/projects/melted-springhare).

**Comment by TheLady** [comment]
Thanks Jeff, I know. I believe I need a name for my one-person team. Right now I have a name for a two-person team.

**Comment by TheLady** [comment]
Okay, thanks. I only saw the spreadsheet that was posted in the Oakland channel on Echo before you sent the link.

**Comment by jeffreywescott** [comment]
What I'm saying is that _that team is_ your one-person project. Try to Shift+Reload in your browser. Sal is _not_ on that team.

<img width="1145" alt="game" src="https://cloud.githubusercontent.com/assets/130597/22440736/adb78fe8-e6e9-11e6-8d13-738b176f6c6f.png">

**Comment by TheLady** [comment]
I'm fine now - the link you sent me made it clear. I did not have a link to that page when I submitted the question, which is why I did not know that Sal had been removed from the team. The only information I had was a screenshot in the Oakland channel that showed the team and both of our names. Is there someplace else I should have looked for the page? Thanks again.

**Comment by jeffreywescott** [comment]
You can always cruise around https://game.learnersguild.org as much as you'd like.

**Comment by TheLady** [comment]
After about thirty minutes, "like" was exhausted :-). But on a serious note, I have been trying to limit my time searching for answers because it's been feeding into a loop that is increasingly triggering and time-consuming. I know that everyone is busy, so by the time I ask the question, I've already spent some time searching for the answers/solutions.  I try to ask for help before the loop pushes me off-track.
