### ISSUE TITLE
Stats incorrect/transposed for player contributions

### ISSUE THREAD

**Issue by needdra** [LearnersGuild/los#161]
Somehow player contributions were reported incorrectly and the players just noticed.  
Cycle 27 - 
players: kousagi1012 & qweenwasabi
both players have confirmed that the contribution stats are transposed. 

kousagi1012 should have 71%
queenwasabi should have 28.999999999999996%

**Comment by heyheyjp** [comment]
@needdra: can you please provide the project name?

**Comment by needdra** [comment]
#tightfisted-waterbuck

**Comment by heyheyjp** [comment]
These names... 🙄  😂

**Comment by needdra** [comment]
no kidding. lol

**Comment by heyheyjp** [comment]
@needdra: does this take into account the new logic for using the figures from the player with the highest bias stats? If I understand recent changes correctly, the system basically identifies the player on a team with the most "accurate" history of contribution estimation and uses only their scores.

**Comment by needdra** [comment]
i'm not sure - we'd need to identify the cycle that change was made. my sense is that the change was effective at cycle 28 or 29. 

however, the learners have said this was a reporting error so it would e unfortunate if the stats stayed the same bc queenwasabi is "more accurate"

**Comment by jeffreywescott** [comment]
The change RE: estimation accuracy was a _retroactive_ change, so it doesn't matter which cycle it was.

**Comment by needdra** [comment]
gotcha. thanks @jeffreywescott

**Comment by heyheyjp** [comment]
@needdra: so these are jacky's contribution ratings. are you asking that the values be changed/that her retro be reopened so that she can change her answers?

**Comment by needdra** [comment]
@prattsj yes. she made a mistake and it's impacting her partner negatively.

**Comment by heyheyjp** [comment]
The retro survey for #tightfisted-waterbuck has been reopened for qweenwasabi.
