### ISSUE TITLE
investigate absent stats for @ameliavoncat

### ISSUE THREAD

**Issue by needdra** [LearnersGuild/los#163]
team #statuesque=gerenuk
cycle 30

players: ameliavoncat & frankiefabuloso

i can see frankie's written feedback but no stats are visible for either player. amelia said she submitted a retro but it didn't have a ton of data bc she was out several days last week. 

please investigate - will these players have stats for last week? do they need to resubmit retros?

**Comment by jeffreywescott** [comment]
We had a bug with stats that has now been fixed. Stats should be there again.
