### ISSUE TITLE
Reviews for teams in succession did not work as expected

### ISSUE THREAD

**Issue by punitrathore** [LearnersGuild/los#164]
### Expected vs. Actual

I completed 2 reviews in succession on Monday. I gave a completeness & quality score of 40 & 50 to team `statuesque-gerenuk` and a score of 80 & 90 to team `cumbersome-shrew`. But it looks like the team `statuesque-gerenuk` ended up getting a score of 80 & 90, while the scores of `cumbersome-shrew` did not get saved. 

Can you also please update the reviews scores for these teams:
1. cumbesome-shrew - completeness:80 , quality:90
2. statuesque-gerenuk - completeness:40, quality:50

Disclaimer: I am 95% sure that I submitted the reviews, so if there a way to look at the logs to confirm/invalidate what I'm saying, that would be AWESOME.

### Steps to Reproduce

N/A

### Environment and Versions

N/A

**Comment by bundacia** [comment]
@punitrathore: I believe that you can use the `/review` command to change your responses to a project review by just resubmitting it. Have you tried that?

**Comment by bundacia** [comment]
Here's what we have in the logs for the `/review` command being used for those projects

```
Feb 06 12:12:33 echo app/web.1:  [lg-game] '/review' invoked with '#cumbersome-shrew ' 
Feb 06 12:19:13 echo app/web.1:  [lg-game] '/review' invoked with '#statuesque-gerenuk -c 80 -c 50' 
Feb 06 12:47:26 echo app/web.1:  [lg-game] '/review' invoked with '#statuesque-gerenuk' 
Feb 06 12:48:05 echo app/web.1:  [lg-game] '/review' invoked with '#statuesque-gerenuk -c 40 -q 80' 
Feb 06 12:48:27 echo app/web.1:  [lg-game] '/review' invoked with '#cumbersome-shrew ' 
Feb 06 12:50:13 echo app/web.1:  [lg-game] '/review' invoked with '#statuesque-gerenuk -c 80 -q 90' 
Feb 06 12:50:50 echo app/web.1:  [lg-game] '/review' invoked with '#cumbersome-shrew ' 
Feb 07 19:15:35 echo app/web.1:  [lg-game] '/review' invoked with '#statuesque-gerenuk' 
Feb 07 19:16:44 echo app/web.1:  [lg-game] '/review' invoked with '#statuesque-gerenuk' 
Feb 07 19:16:59 echo app/web.1:  [lg-game] '/review' invoked with '#cumbersome-shrew ' 
```
