### ISSUE TITLE
Add "Levels" tab to Admin UI or make headers sortable

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#165]
### Expected vs. Actual

_In addition to being able to view stats by Player & by Project, it would be useful to view them by Level, to see at a glance who's where. I realize this data is available on the users tab, but since the headings aren't currently sortable, I can't get a picture all at once of who's where. So I guess, a different fix would be to make the column headers sortable (i.e. sort by name, sort by name, Level, Elo, or XP)._

### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._

### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
Tracked here: https://app.clubhouse.io/learnersguild/story/396/tables-should-be-sortable-in-the-admin-ui
