### ISSUE TITLE
Voting choice rank problem.

### ISSUE THREAD

**Issue by phoniks** [LearnersGuild/los#167]
<img width="406" alt="screen shot 2017-02-13 at 9 31 30 am" src="https://cloud.githubusercontent.com/assets/7213762/22894984/c0278bb0-f1cf-11e6-973a-3e4020acacce.png">

In the picture above, I voted for two goals, and they each have one vote a piece - my own votes.  Since my number one vote should get chosen first and my number two vote should be chosen second if the votes were finalized at this point, I would expect that they would appear in the list in that order as well, particularly since they are both individual goals and should, therefore, be more heavily weighted in the group assignments.

**Comment by jeffreywescott** [comment]
Hi, @phoniks. The little `1st` or `2nd` indicator on the goal line indicates your preference ordering. We currently don't do a "secondary" ordering on the sort based on user preference to handle the edge-case that you point out. But rest assured that, when the project-formation algorithm runs, it will take into account your preferences as indicated by the `1st` and `2nd` badges.

Sorry for the confusion.

**Comment by jeffreywescott** [comment]
I've pulled this suggestion into our list to be considered.
