### ISSUE TITLE
Fix the amount of hours for cycle 31 for @yaseenagag

### ISSUE THREAD

**Issue by yaseenagag** [LearnersGuild/los#168]
My handle is @yaseenagag

I need to correct my hours for cycle 31 from 25 to 10.  I missed one full day and two half days.  The correct hours are 10.

Please find listed below my info for cycle 31.

#122 [L1.2]: Blogetty-blog-blog: Make A Blog Site
Feb 6 - Feb 13 [cycle 31]
25 hours [team total: 35]
70% contribution

Team Name: elastic-bushbaby

**Comment by yaseenagag** [comment]
@jeffreywescott @bundacia can i get an update on this when possible?

**Comment by bundacia** [comment]
@yaseenagag, I've re-opened your survey so you can go in and change your answer using `/retro`
