### ISSUE TITLE
Profile Name Changing Bug

### ISSUE THREAD

**Issue by jrobcodes** [LearnersGuild/los#17]
### Expected vs. Actual

I changed my name on my profile page, and it introduced @mention artifacts.
### Steps to Reproduce
1. Go to My Account > Profile
2. Change the `Username` field (I changed to `jrob`, from `jrob8577`)
3. Save

At this point, the account name displayed in the upper left hand corner updates to `jrob`. Refreshing the page changes the avatar to my initials.  I had to log out and in again to reset to `jrob8577` (which happened automatically when I signed in; I did not change my username back).

In the `@` mention list, I still see `jrob`.
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
I've disabled the ability for people to modify their avatar or handle. Both will always be synchronized to whatever is in GitHub. I've also updated the username for any old messages that belonged to:
- EthanStark --> EthanJStark
- jaredatron --> deadlyicon
- jrob --> jrob8577
- Thomas_Smith --> TS22082
