### ISSUE TITLE
ELO shown as increasing by entire amount rather than difference. -bug

### ISSUE THREAD

**Issue by mantinone** [LearnersGuild/los#170]
## Expected vs. Actual

When looking at the stats page for #insidious_grebe, my ELO is 1049.  For the previous week, a solo project, #fluffy_mantis, it is shown as null.  For the week before that, #cumbersome_shrew, it is 1017.
The green numbers next to the stat that show how it has changed should show +32 for #fluffy_mantis. 
Instead, it shows +1049.

### Steps to Reproduce

Simply view my stats page to see the problem.  I think that this problem might exist on any stats page where the previous week was a solo project, where ELO is shown as null.

### Environment and Versions

I am using the latest version of Firefox.

**Comment by jeffreywescott** [comment]
Hi, @mantinone ... that's a great catch! Thanks for the report.

**Comment by jeffreywescott** [comment]
@mantinone -- a fix for this will be deployed in the next 15 minutes or so. Thanks again for the report.
