### ISSUE TITLE
Adjust my contribution for cycle 33 from 100% to 70% Data

### ISSUE THREAD

**Issue by yaseenagag** [LearnersGuild/los#171]
axiomatic-ringtail
State: COMPLETE
#176 [L1]: Core Vanilla Javascript [Team Drills & Practice]
Feb 21 - Feb 27 [cycle 33]
15 hours [team total: 15]
100% contribution

**Comment by jeffreywescott** [comment]
@yaseenagag: please ask a moderator for help with this -- they now have a tool that let's them unlock a retrospective for you to modify.
