### ISSUE TITLE
Clarify missing ELO stat for @silentsoundsz 

### ISSUE THREAD

**Issue by needdra** [LearnersGuild/los#174]
### Expected vs. Actual

_Expected to see 1000 ELO for Stephanie McGrath/silentsoundz. Her first cycle was C33. She worked on 2 solo projects: 
#zonked-gazelle C33
#natural-grison C34
If seeded w/ 1000 ELO then that stat should be visible in the UI but it isn't on my end. 

Is this an error?

**Comment by jeffreywescott** [comment]
We are tracking this bug already. Basically, it's an annoying rendering bug due to the fact that solo projects don't affect Elo or XP, they don't get rendered properly because of the way the data gets passed from the server to the client. I'll leave this bug open until we address it.
