### ISSUE TITLE
Add user photos to https://game.learnersguild.org/users

### ISSUE THREAD

**Issue by ghost** [LearnersGuild/los#175]
This is a suggestion and not for a bug.  I propose adding our Echo photos to this page: https://game.learnersguild.org/users

That way we can easily see each others' name, username, and photo in one place digitally.  Several folks have expressed a desire to have a digital version of the photo board.  I don't know if this data already exists in Echo, but Level (or start month), House, Github might also be useful fields to add.

**Comment by jeffreywescott** [comment]
Duplicate of #148.
