### ISSUE TITLE
Clarify Stat Totals on game.learnersguild.org

### ISSUE THREAD

**Issue by mistakeets** [LearnersGuild/los#176]
### Expected vs. Actual

For the past week project (cycle 36) my estimation accuracy for the project was 100% with a bias of 0%, therefore I expected my total average estimation accuracy to go up. Instead it went down by 12, and in the total section it shows 30.83% percent. A similar issue also happened during cycle 34. 

Based on this issue, it also appears that my estimation accuracy did not increase on the left hand side of the user profile UI . Under my picture it still shows the same percentage for estimation accuracy that it did before cycle 36 started. I was expecting my estimation accuracy to go up about 2 or 3 percent.

**Comment by lumodon** [comment]
## Problem
I am experiencing the same problem. My numbers are the following: 
## Expected vs. Actual
cycle 33: Est. Accuracy: 78%, 91.17%
cycle 34: Est. Accuracy: - - (solo project)
cycle 35: Est. Accuracy: 80% 72.5%
cycle 36: Est. Accuracy: - - (solo project)
cycle 37: Est. Accuracy: 89% 56.67%

## Description
I do believe that solo projects are being counted as 0% and potentially being counted for the denominator of total projects when calculating mean average? Or if using rolling average, some how solo projects aren't being ignored.

**Comment by jeffreywescott** [comment]
We are looking into this.

**Comment by jeffreywescott** [comment]
This should now be fixed.
