### ISSUE TITLE
Players lose ELO when third team member is added to team of two

### ISSUE THREAD

**Issue by breyana** [LearnersGuild/los#177]
### Expected vs. Actual

I noticed this issue when analyzing my ELO progression and noticing large drops when I'm placed into a team that has had a 3rd member added onto it. In teams of three even with greater than expected 1/3 contribution, my ELO had fallen. 

My theory is that the ELO calculation is expecting 50% contribution instead of roughly 33% contribution. 

Projects Effected:
https://game.learnersguild.org/projects/shy-serval
https://game.learnersguild.org/projects/huge-manatee

Overall Projects: https://game.learnersguild.org/users/breyana

### Steps to Reproduce

1. Have the algorithm create a 2 person team
2. Have a 3rd person added to the team
3. In retros, divide contribution equally as possible between three people

Result:
ELO drops for the players 

Expected Result: 
ELO stays the same for even contribution

**Comment by jeffreywescott** [comment]
We are looking into this.

**Comment by breyana** [comment]
@jeffreywescott Updated the issue with a little more clarity. It seems alright for team-size 3 goals, but seems broken for team size 2 goals that have a 3rd member added. 

Can this be retroactively fixed?

**Comment by heyheyjp** [comment]
No longer relevant.
