### ISSUE TITLE
Can not sign in to Echo from the play book error sign-up is by invitation only right now.

### ISSUE THREAD

**Issue by vbrazelton916** [LearnersGuild/los#178]
### Expected vs. Actual

Expected to log into Echo from the playbook  vs Receive a error message to sign-up is by invitation only right now.  

_What were you attempting to do? 
When clicking on the link to sign in to Echo from the Playbook it provides an error message that that it is by invite only
What actually happened? Please provide your project name and/or the cycle number if applicable._
When clicking on the link to sign in to Echo from the Playbook it provides an error message that that it is by invite only
### Steps to Reproduce
When clicking on the link to sign in to Echo from the Playbook it provides an error message that that it is by invite only
_How can you reproduce the bug? Include as much detail as you can._
When clicking on the link to sign in to Echo from the Playbook it provides an error message that that it is by invite only
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
Hi, @vbrazelton916. What is the exact link that it is in the playbook that you're referring to? I see this one (https://echo.learnersguild.org/) on this page (https://playbook.learnersguild.org/Game_Manual/Echo.html). Is that what you mean?

Echo sign-up _is_ invite only, and the invitation comes as part of the welcome email during on-boarding. Once you've signed-up with your invite code, you should be able to sign-in again at any time.

**Comment by jeffreywescott** [comment]
Closing (no response).
