### ISSUE TITLE
Accuracy decreases when completing solo projects

### ISSUE THREAD

**Issue by lumodon** [LearnersGuild/los#179]
### Expected:
I expect solo projects to not modify, up or down, my accuracy
### Actual:
After completing a project following a solo project, my total accuracy went down even though my project accuracy went up. This implies that my total somehow decreased previously, my best guess is that the solo project counted an invisible decrease in accuracy.

## Steps to Reproduce
1. Note your total accuracy.
2. Spend a week doing a solo project. 
3. After the solo project, spend a week doing a team project. 
4. Collude with your partner to get 100% accuracy. 
5. Watch that even though your project accuracy was 100%, your total accuracy decreased.

## Environment and Versions
Echo?
Using [Project History Page](https://game.learnersguild.org/users/lumodon) to see accuracy over time.

## Evidence:
<img width="507" alt="cycle32" src="https://cloud.githubusercontent.com/assets/10302608/24719762/ca2db376-19ef-11e7-9694-46eec924eb43.png">
<img width="508" alt="cycle33" src="https://cloud.githubusercontent.com/assets/10302608/24719770/cebb129e-19ef-11e7-9a6f-e6015687ac39.png">
<img width="482" alt="cycle34" src="https://cloud.githubusercontent.com/assets/10302608/24719775/d2877002-19ef-11e7-9a94-1aa7f1f0b8d2.png">
<img width="492" alt="cycle35" src="https://cloud.githubusercontent.com/assets/10302608/24719782/d6dfb65a-19ef-11e7-8bde-7bc220f6efa3.png">
<img width="473" alt="cycle36" src="https://cloud.githubusercontent.com/assets/10302608/24719787/d99e072a-19ef-11e7-81bf-5f2c6ac593a1.png">
<img width="499" alt="cycle37" src="https://cloud.githubusercontent.com/assets/10302608/24719789/dc285a90-19ef-11e7-9e2b-07ad21adc8fc.png">

**Comment by jeffreywescott** [comment]
We are looking into this.

**Comment by jeffreywescott** [comment]
This has been fixed!
