### ISSUE TITLE
possible bug - retro not displaying in admin UI

### ISSUE THREAD

**Issue by needdra** [LearnersGuild/los#180]
#Shaky-Vulture
Cycle 36
jnware7 appears not to have completed the retro but we checked and the system isn't reporting any pending retros. his partner did not enter 100% completion for herself but the system is reporting that as her entry.

**Comment by needdra** [comment]
actually - i'm seeing the same thing across a two other projects. The learners report submitting their retros. The system says they have no pending retros, but the stats are not visible in the UI. 

This is true for:
brawny-frogmouth
State: COMPLETE
#196: Dive Into UNIX and Bash
Mar 13 - Mar 20 [cycle 35]

capricious-hoopoe
State: COMPLETE
#69 [L1]: Simple Book Store
Mar 27 - Apr 3 [cycle 37]

**Comment by heyheyjp** [comment]
Definitely was a bug. There was a little bit of cleanup that wasn't caught for a question removed from a previous version of the retro survey. Fix has been applied, and anyone who couldn't access their retros but should have been able to should now be good to go.
