### ISSUE TITLE
Estimation accuracy not computed correctly when one player did no work

### ISSUE THREAD

**Issue by bundacia** [LearnersGuild/los#182]
From Ethan:

Hi support team! Cycle 37, #public-bushbuck, my partner was out the entire week, and I marked 100% contribution . . . which took my accuracy down enormously and knocked me down to Level 1. If someone could help me correct this, that'd be awesome. Thanks!

[Clubhouse Ticket already created](https://app.clubhouse.io/learnersguild/story/2107/estimation-accuracy-not-computed-correctly-when-one-player-did-no-work)

**Comment by bundacia** [comment]
cc: @ethanjstark

**Comment by jeffreywescott** [comment]
This has been fixed.
