### ISSUE TITLE
Discrepancy in expected estimation accuracy

### ISSUE THREAD

**Issue by Moniarchy** [LearnersGuild/los#183]
### Expected vs. Actual

During cycle 33, where my project estimation accuracy was 99%, my total accuracy nevertheless dropped 64.42 points to 30.83%.
<img width="879" alt="screen shot 2017-04-14 at 3 49 10 pm" src="https://cloud.githubusercontent.com/assets/18104615/25058002/22a1dea6-212a-11e7-8f54-6f4eb7927fa0.png">

Since then, though my estimation accuracy has increased weekly, my current accuracy score shows as 59%.
<img width="883" alt="screen shot 2017-04-14 at 3 56 36 pm" src="https://cloud.githubusercontent.com/assets/18104615/25058104/04359614-212b-11e7-9ff2-c057d97a4e9a.png">

However, my estimation accuracy as it shows under my account is 89.83%.
<img width="237" alt="screen shot 2017-04-14 at 3 54 00 pm" src="https://cloud.githubusercontent.com/assets/18104615/25058077/c48b8a32-212a-11e7-80c6-c8360b2fe0be.png">

### Environment and Versions

On Chrome, visited https://game.learnersguild.org/users/Moniarchy.

**Comment by mantinone** [comment]
I wanted to note, I've seen this bug as well.  Total Accuracy seems to drop sharply after weeks where I was on a solo project.

**Comment by jeffreywescott** [comment]
This has been fixed.
