### ISSUE TITLE
Stats need to be updated

### ISSUE THREAD

**Issue by sashajustice** [LearnersGuild/los#184]
### Expected vs. Actual

 I had my retro stats updated last week and it's not reflecting the change.  The group is #scrawny-Currasow. 
_What were you attempting to do? What actually happened? Please provide your project name and/or the cycle number if applicable._

Cycle 38 

### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._

### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_
OS

**Comment by jeffreywescott** [comment]
Hi, @sashajustice -- we just re-computed everyone's stats, so hopefully the change is reflected now. Please let us know if that's not the case by reopening this issue.
