### ISSUE TITLE
XP.v2 score not showing

### ISSUE THREAD

**Issue by Maighdlyn** [LearnersGuild/los#187]
### Expected vs. Actual
project name: questionable-rabbit
cycle#: 42
My 'XP.v2' and 'XP.v2 Pace' scores are still not showing up and my state is still showing "REVIEW" on my cycle 42 project which was completed over a week ago.

### Steps to Reproduce
It's always what happens when I look at my stats. I've been checking on it throughout the week and it's always the same.

### Environment and Versions
Tried in Chrome, Safari, and Brave, shows up the same in each.

![screen shot 2017-05-13 at 6 56 27 pm](https://cloud.githubusercontent.com/assets/18200365/26030732/1d1cc98a-3810-11e7-92b4-9649b9fde507.png)

**Comment by bundacia** [comment]
@Maighdlyn, first off, thank you for such a well written-bug report! Screenshots and everything. I love it.

The reason you're not seeing XP.v2 yet is that you're project is still in the `REVIEW` state. That means that the system is waiting for your coach to review your project before calculating XP.v2. The reason we have to wait for the coach's review is that the XP.v2 you earn depends on the project completeness, and we rely on coach's assessment of that. As soon as @Moniarchy reviews your project it will move into the `CLOSED` state and you're XP.v2 will be calculated and displayed.

**Comment by Moniarchy** [comment]
Sorry for my negligence. I'm reviewing the rest of my projects right now. :)
