### ISSUE TITLE
Offensive Team Names Assigned By Algorithms

### ISSUE THREAD

**Issue by lisabronwyn** [LearnersGuild/los#191]
### Expected vs. Actual

Learners shouldn't receive offensive team names (for their weekly projects) via the algorithm. 

This week I was assigned to the "obese-mara" goal and another learner mentioned that they were assigned to team 'alcoholic-lark'.

**Comment by jason00111** [comment]
Here are some I've been assigned:
arrogant
deceitful
fumbling
ugly
chunky

**Comment by mKleinCreative** [comment]
Jobless is another one

**Comment by bundacia** [comment]
oof, sorry folks. We use a npm library for generating random names, which we tweaked to try to filter out awful ones. Apparently we missed some. ☹️

**Comment by bundacia** [comment]
ok, I've added those words to the filter. For reference, the package we use for generating team names is [animal-id](https://www.npmjs.com/package/animal-id). And then we explicitly filter out the following:

```javascript
export const FILTERED_WORDS = [
  // adjectives
  'alluring',
  'bawdy',
  'dead',
  'dirty',
  'erect',
  'female',
  'hard',
  'hot',
  'lewd',
  'macho',
  'male',
  'naughty',
  'obscene',
  'racial',
  'vulgar',
  'womanly',
  'youthful',
  'arrogant',
  'deceitful',
  'fumbling',
  'ugly',
  'chunky',
  'jobless',
  'alcoholic',
  'obese',

  // animals
  'beaver',
  'booby',
  'dik',
  'nutcracker',
  'screamer',
  'woodcock',
]
```

Let me know if anything else creepy comes up that we missed.
