### ISSUE TITLE
Unable to start using echo

### ISSUE THREAD

**Issue by bluemihai** [LearnersGuild/los#2]
### Expected vs. Actual

I was attempting to follow the single-sign on link emailed to me to create an account.
### Steps to Reproduce

Chatting with Jeffrey, we think that the problem is that my spotty wifi disconnected, and something didn't get copied right.
### Environment and Versions

Chrome originally (also tried in FF, and in Rocket.chat+ app with same results)

**Comment by jeffreywescott** [comment]
This should now be fixed.
