### ISSUE TITLE
Multiple user names / handles for same person

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#20]
### Expected vs. Actual

_Noticing that people seem to have multiple user names within Echo (EthanStark, EthanJStark, EJStark, Thomas_Smith, TS22082) - super confusing! There should only be one if they have a single Github handle, right? Hard for me to tell which handle to use if I want to tag someone
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jrobcodes** [comment]
This is related to #17

**Comment by jeffreywescott** [comment]
I've disabled the ability for people to modify their avatar or handle. Both will always be synchronized to whatever is in GitHub. I've also updated the username for any old messages that belonged to:
- EthanStark --> EthanJStark
- jaredatron --> deadlyicon
- jrob --> jrob8577
- Thomas_Smith --> TS22082
