### ISSUE TITLE
Unable to see certain people's photos

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#21]
### Expected vs. Actual

_When I click on these people's avatar photos, I see the large version pop up on the righthand side:
- Shereef
- NeEddra 
- Mihai

_When I click on these people's avatar photos, the right panel opens, but there's no large version of the picture, just the button that says "conversation". I can't tell if the photo and name info are just being cut-off, higher on the page, or if they don't exist at all:
- Thomas_Smith but NOT for TS22082 (multiple handles)
- jrob
- EthanStark but NOT FOR EthanJStark (multiple handles)
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
Also related to https://github.com/LearnersGuild/los/issues/17

We need to disable the ability for people to mess with their profiles inside of echo. These bugs are all fallout from that.

**Comment by jeffreywescott** [comment]
I've disabled the ability for people to modify their avatar or handle. Both will always be synchronized to whatever is in GitHub. I've also updated the username for any old messages that belonged to:
- EthanStark --> EthanJStark
- jaredatron --> deadlyicon
- jrob --> jrob8577
- Thomas_Smith --> TS22082
