### ISSUE TITLE
Many commands should notify other people besides issuer

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/los#22]
### Expected vs. Actual

_What were you attempting to do? What actually happened?_

Issuing `/project set-artifact ...` should notify the rest of the team that this has been set, as an example. Other commands should be reviewed to ensure that proper notifications are sent.
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by tannerwelsh** [comment]
Thanks @deadlyicon for noticing

**Comment by jeffreywescott** [comment]
Closed as part of https://github.com/LearnersGuild/game/issues/247
