### ISSUE TITLE
Staging environment?

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/los#25]
Now that we're up and running in prod (🎉), should we set up a shared dev/staging environment?

`https://echo-staging.learnersguild.org`

**Comment by jeffreywescott** [comment]
Let's definitely talk about this. In general, I am 1000% against staging environments as a concept (continuous delivery #ftw -- happy to explain my reasoning), but I _am_ in favor of the idea of getting our development and production environments as sync'ed as possible. IMO, the best approach to this is to Docker-ize our setup. Let's discuss along with the rest of the "non-user-facing" stuff we wanna chat about.

**Comment by jeffreywescott** [comment]
Issue moved to [LearnersGuild/echo-chat #47](https://github.com/LearnersGuild/echo-chat/issues/47) via [**ZenHub**](https://www.zenhub.com/)
