### ISSUE TITLE
Suggested feature: show user's full name on hovering over username

### ISSUE THREAD

**Issue by bluemihai** [LearnersGuild/los#28]
As a new user, I would like to quickly know who posted what (even before I memorize everybody's github/username), so that I can feel a part of an actual community and engage fully with a minimum of frustration.

The best way I can think of is showing the full name on hovering over the username... either in a message window (currently no hover text) or in direct messages (currently hover text is just the username again).

**Comment by jeffreywescott** [comment]
If you click on the player's name, a panel will slide out with their profile info.
