### ISSUE TITLE
Only import the default/primary email address from a user's github account

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/los#29]
My echo profile has every email address associated with my GitHub account, which is unnecessary and perhaps confusing for folks who'd want to send me an email. Most of them are linked only for work on a specific org's repos. My expectation here would have been that only my default/primary email address is imported from GitHub and is shown in my Echo profile.

**Comment by jeffreywescott** [comment]
Fair point. In IDM, we allow the user to save their preferred address, and change it later (via the `/profile` command), but there's no need to pull all the info into echo.

**Comment by jeffreywescott** [comment]
Closed, as per https://github.com/LearnersGuild/rocketchat-lg-sso/issues/35
