### ISSUE TITLE
Inifinite loop on signup attempt

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/los#30]
from @shereefb:

video screen cap:
http://screencast.com/t/Ws70lHbz

expected:
- visits `echo.learnersguild.org`
- redirected to idm sign in page
- clicked button to authenticate using github
- redirected **back** to echo and able to use the chat app

actual:
- visits `echo.learnersguild.org`
- redirected to idm sign in page
- clicked button to authenticate using github
- lands on the idm profile page

additional useful info?
- logged in day before with both a moderator account in the `oakland` chapter and a player account in the `play-test` chapter. due to an issue this caused with voting panel functionality, the player account was deleted.
- changes to `idm` authentication handling were deployed (after successful login) the day before

not clear to me at all that either of these have something to do with the occurrence of this issue.

**Comment by jeffreywescott** [comment]
This happened because @tannerwelsh and @shereefb were in the `player` role but didn't have a corresponding record in the `players` table in game. We should recover gracefully from this.

**Comment by jeffreywescott** [comment]
Closed as per https://github.com/LearnersGuild/rocketchat-lg-sso/issues/32
