### ISSUE TITLE
Text I type does not wrap to the next line, it continues off the screen. 

### ISSUE THREAD

**Issue by harmanTheCarMan** [LearnersGuild/los#31]
### Expected vs. Actual

_What were you attempting to do? What actually happened?_
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by harmanTheCarMan** [comment]
Expected to wrap text. Text continued off screen.
Reproduce by resizing the browser window so that the window may be 2/3 of the screen, then type your response. Environment: mac, google chrome, 2/3 of screen used on large desktop monitor.

**Comment by jeffreywescott** [comment]
I cannot reproduce this, @harmanlearns -- can you paste a screenshot?

**Comment by harmanTheCarMan** [comment]
@jeffreywescott issue can be closed. I think it was just a random echo bug.
