### ISSUE TITLE
Hard to see message numbers in Echo

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#33]
The numbers in Echo are hard to see - much harder than the numbers in Slack. Not sure if it's about the color combo, or the size, but it's hard for me to figure out how many messages are pending my reading at a quick glance. 

For that matter, the channel names seem harder to read as well, and it's harder to tell when there's a new message in a channel (when it's bolded). All these comparisons are to Slack.

Thanks for considering :)

**Comment by jeffreywescott** [comment]
This should be fixed.
