### ISSUE TITLE
the sliders in the retro form are too small to increment 1% at a time

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/los#37]
(reported by @deadlyicon)
### Expected vs. Actual

I wanted to adjust someone's relative contribution by 1%, but couldn't because the sliders were too small.
### Steps to Reproduce

`/retro`
### Environment and Versions

@deadlyicon -- please update this with which client / os you used? Native app? Chrome?

**Comment by bluemihai** [comment]
+1 for me with both Chrome and Rocket.chat

**Comment by jeffreywescott** [comment]
This should have been addressed with the most recent deploy of echo. Please re-open if it comes up again.
