### ISSUE TITLE
Echo API for projects

### ISSUE THREAD

**Issue by sydroth** [LearnersGuild/los#38]
Tanner suggested I submit this here- for projects that require learners data, we were wondering if there's an ECHO api we can use to get basic data. In this case, we want to know which learners have completed which projects.

**Comment by EthanJStark** [comment]
I would also very much like to have access to an Echo API; very relevant to a project that 11 of us are working on. Thanks, Echo team!

**Comment by devonwesley** [comment]
I third this

**Comment by jeffreywescott** [comment]
This is a great idea, and something we definitely hope to provide in the future.
