### ISSUE TITLE
Provide a way to see all your /review states w/ one command

### ISSUE THREAD

**Issue by phoniks** [LearnersGuild/los#39]
### Expected vs. Actual

_What were you attempting to do? What actually happened?_

While reviewing projects, I found myself wanting to be able to type "/review -a" to get a list of all the projects and their current status.
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._

No bug, just a suggestion.
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

Chrome on OSX

**Comment by jeffreywescott** [comment]
Thanks for reporting this, @phoniks ... have you tried `/project list -r`?

**Comment by jeffreywescott** [comment]
This is now available in the UI.
