### ISSUE TITLE
Info Panel Bug

### ISSUE THREAD

**Issue by jrobcodes** [LearnersGuild/los#4]
### Expected vs. Actual

Clicking on the group icon in the right toolbar, I expected to see a list of the people in the room.  I saw that list, but washed out, underneath SJ's information (which was the last piece of information I had viewed in the right info area). Image attached.
### Steps to Reproduce

Click on a user's icon to reveal the user information in the right hand toolbar.  Then, click on the Group icon to reveal the list of people in the room.  The former user information panel appears above the group listing, with the group listing washed out (opaque).
### Environment and Versions

Chrome.
![screen shot 2016-07-01 at 11 08 30 am](https://cloud.githubusercontent.com/assets/838110/16530362/9e6e3c4a-3f7c-11e6-9f64-05f0ab12f120.png)

**Comment by jeffreywescott** [comment]
Should be fixed now.
