### ISSUE TITLE
Bind up arrow to command history

### ISSUE THREAD

**Issue by bluemihai** [LearnersGuild/los#41]
### Expected vs. Actual

When reviewing or voting, I often hit the up arrow expecting to see and edit my last command.
I didn't even realize what happened until I just tried it again to reproduce this bug...  What does happen is that I see my past messages come up and I can cycle through them.

I would expect that the up arrow **only** bring back my commands...  but I rarely if ever have a need to say the same message twice, so I don't see the point of that.

FWIW, Slack does use up arrow to bring up your last message [not command], but also puts it in edit mode.  This too would be a slight UX improvement in my opinion, although it's not intuitive to me.
### Steps to Reproduce

Not a bug, just a UX suggestion
### Environment and Versions

Chrome on Mac

**Comment by jeffreywescott** [comment]
@bluemihai -- thanks for this suggestion! **TL;DR** -- as much as we'd like to support this, the underlying Rocket.Chat architecture makes it prohibitively difficult.

#### More Detail

Essentially, there is a table that stores messages, but none that stores `/slash` commands; they are ephemeral.  If we were to support this, we'd need to make huge deviations from Rocket.Chat mainline, which (for many reasons) we are trying to avoid.
