### ISSUE TITLE
changing goal issue name during voting splits votes

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/los#42]
### Expected vs. Actual

votes should be based on issue number not name
### Steps to Reproduce
1. vote for a goal issue
2. change the goal issue name
3. have someone else vote for the same issue number
4. see how votes are split
### Environment and Versions

chrome

**Comment by prattsj** [comment]
This doesn't make sense. Votes _are_ based on the issue number. :/

**Comment by heyheyjp** [comment]
Seems to be just a rendering issue. Votes are ultimately counted by goal ID when it comes to forming projects, but when displaying voting results in the flex panel, they're grouped by url and title/name.

**Comment by jeffreywescott** [comment]
Tracked here: https://app.clubhouse.io/learnersguild/story/2097/changing-goal-issue-name-during-voting-splits-votes
