### ISSUE TITLE
Professional players never get what they vote for

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/los#43]
### Expected vs. Actual

I want to get the projects I vote on. 
### Steps to Reproduce
1. Be a professional player
2. Vote for projects
3. Never get on those projects
### Environment and Versions

LOS v1.1?

**Comment by jeffreywescott** [comment]
Related: https://github.com/LearnersGuild/learning-os-software/issues/148

**Comment by jeffreywescott** [comment]
Pro players are no longer voting.
