### ISSUE TITLE
cannot close echo panel

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/los#44]
### Expected vs. Actual

![](https://dl.dropboxusercontent.com/u/1090585/survey%20could%20not%20be%20loaded.png)
### Steps to Reproduce

you cannot close the window that comes up with you try and retro a team you're not on
### Environment and Versions

chrome

**Comment by heyheyjp** [comment]
@deadlyicon: if you dismiss the alert at the bottom and try closing it, does that work?

**Comment by jeffreywescott** [comment]
This is an overall UX fail. I think we need a tab on the RHS that can open / close all of our panels.

A workaround is to type `/profile` 2-3 times, because `/profile` does toggle rather than open.

**Comment by heyheyjp** [comment]
I don't disagree, but there's also just something weird that's up with this snackbar behavior. They always prevent interaction with the window, and I think this is a bug in react-toolbox.

**Comment by heyheyjp** [comment]
https://github.com/react-toolbox/react-toolbox/issues/178

**Comment by jeffreywescott** [comment]
Yeah ... good point.

In this case, though, there's no option to close the panel within the page, so ...

**Comment by heyheyjp** [comment]
Ah, that's true. Guess we could add a Close button. :)

**Comment by jeffreywescott** [comment]
Yeah ... definitely.

**Comment by harmanTheCarMan** [comment]
What I have done in this situation is clicked on a different "tab" on the sidebar i.e. users tab and then clicking it again causes it to close. Sort of a workaround. @deadlyicon
