### ISSUE TITLE
include "quality" section to goal template

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/los#45]
### Expected vs. Actual

what does quality mean? I think reviewing players need some guidelines about what quality means for the project.

**Comment by jeffreywescott** [comment]
Would you expect this to come from the command help or the moderator? It seems like we might want this to be somewhat flexible depending on the type of game being played (e.g., LOS may eventually be used for enrollment games). WDYT?

**Comment by jeffreywescott** [comment]
@shereefb is this something that should be addressed in software or moderation?

**Comment by shereefb** [comment]
We now have a quality rubric as part of the issue metric. 
The definition of quality is meant to be ambiguous so that teams take the effort to define it at the beginning of their learning goal.

@deadlyicon is this still an open issue for you?

**Comment by jeffreywescott** [comment]
No response after months. Closing.
