### ISSUE TITLE
I never know how to answer this quetion

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/los#46]
I never know how to answer this question:

```
Rate your agreement with the following statement: "I'm a better software developer after working with @[username]"
```

What does better mean? Does it mean:
- i learned something?
- they inspire me?

I'm unclear about this so I always but "agree" or "somewhat agree" so I'm probably not giving useful feedback.

**Comment by harmanTheCarMan** [comment]
I do the same and a part of it became a mix of how much they helped me with interpersonal skills as well...

**Comment by jeffreywescott** [comment]
@shereefb -- is this something we want to address in software or moderation?

**Comment by shereefb** [comment]
I'll bring it up in moderation next friday and see how people respond. Stay tuned.

**Comment by jeffreywescott** [comment]
The questions have been modified a lot since this was filed. No longer relevant.
