### ISSUE TITLE
Trouble setting artifact

### ISSUE THREAD

**Issue by phoniks** [LearnersGuild/los#47]
### Expected vs. Actual

I _think_ I followed the instructions correctly to set the artifact for our project at the beginning of the week, but when it came time to review projects the artifact did not appear to be set.  When attempting set them again at the end of the week I encountered the following error:

<img width="973" alt="screen shot 2016-08-05 at 3 53 00 pm" src="https://cloud.githubusercontent.com/assets/7213762/17452588/568efb16-5b25-11e6-92eb-0b54e42d40ac.png">

Here's a screenshot of the originally set artifact:

<img width="877" alt="screen shot 2016-08-05 at 3 53 39 pm" src="https://cloud.githubusercontent.com/assets/7213762/17452593/6796503a-5b25-11e6-8afb-bdb49f166ea7.png">

The first time I tried to set I was in my project groups chat - the second time I was in the Oakland chat.  Not sure if that makes any difference
### Steps to Reproduce

Set an artifact on Monday morning.  Come back to it Friday afternoon. 
### Environment and Versions

I'm on Chrome in OSX

**Comment by phoniks** [comment]
Shareef suggested removing the https and using normal http and that seems to have overcome the problem.

**Comment by jeffreywescott** [comment]
I believe this has been fixed. We're also working on better error messages.
