### ISSUE TITLE
vote list sort order based on 1st and 2nd vote

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/los#49]
### Expected vs. Actual

right now it looks like some projects have more votes but when the #1 item has the largest number of votes based on 2nd votes it could, and has, mislead the voting and the final chosen projects were in the 2nd and 3rd position. 

Is there anyway to update the life voting list with sorting based on 1st and 2nd votes?

**Comment by jeffreywescott** [comment]
@prattsj, is it universally true that people's 1st votes take precedence over their 2nd? @deadlyicon points out a confusing UX issue where the _total_ number of votes (which is how things are sorted) can be misleading and cause people to vote differently.

**Comment by heyheyjp** [comment]
@jeffreywescott @deadlyicon: I think we should move away from displaying the number of votes altogether. A better experience might be to just basically run the project formation algo (or some subset of it) to simply show goal group ranking rather than the awkward and confusing vote counts.

**Comment by heyheyjp** [comment]
> is it universally true that people's 1st votes take precedence over their 2nd?

Not sure what you mean by taking precedence exactly. We attempt to accommodate their 1st choice before attempting to accommodate their 2nd, of course, but both are subject to dismissal if they don't shake out to be for the most popular votes.

**Comment by bundacia** [comment]
Seems like total vote count is still the best indicator of what the "most popular" goals are. The algorithm just takes into account more than popularity. Maybe the solution here is just to figure out a way to communicate that these "votes" are suggestions for what to work on, not an election where the voice of the people is king. Maybe we need to stop calling them votes and start calling them "preferences" or "project wish list" or something?

**Comment by jeffreywescott** [comment]
@tannerwelsh, fearless in his game mechanics and `ux` roles, foresaw this confusion: https://github.com/LearnersGuild/game/issues/390

**Comment by jeffreywescott** [comment]
Tracked here: https://app.clubhouse.io/learnersguild/story/2089/votes-should-be-secondarily-sorted-by-rank
