### ISSUE TITLE
Echo /project set-artifact BUG -Can't Set BUG Label on Issue

### ISSUE THREAD

**Issue by nicosesma** [LearnersGuild/los#51]
### Expected vs. Actual

I was trying to set the artifact for the group project before the review cycle began but I got an error message that read:
/project set-artifact #ashamed-opossum https://github.com/rachel-ftw/LG-simple-JS-library
_Error:_ [object Object]

When I tried to see if I could review the project I was met with the same error message:
/review #ashamed-opossum
_Error:_ [object Object]
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
I think that someone set the artifact at the beginning of the week, but since I could not access the artifact with the /review command, I tried to set it again and was met with the error message in both cases.
### Environment and Versions

I am using chrome.

**Comment by jeffreywescott** [comment]
This has now been fixed. We are also working on better error messages.
