### ISSUE TITLE
Github username change issue

### ISSUE THREAD

**Issue by harmanTheCarMan** [LearnersGuild/los#53]
### Expected vs. Actual

_What were you attempting to do? What actually happened?_
I changed my github username to match my email and website. It caused echo to have issues in terms of private groups and having the same permissions as a user in channels.

I can not see any of the previous private channels and no more gear icon next to a post in certain channels.
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
-Change github username
-try to use echo again in same channels as previous username
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_
Chrome on Mac.

**Comment by jeffreywescott** [comment]
Thanks for reporting this, @harmanlearns. Is this blocking you from being able to work / collaborate (trying to prioritize)?

**Comment by harmanTheCarMan** [comment]
@Jeffrey: This is not blocking me from working right now. I can send and receive messages.

This can be fixed  when there is time available. I mainly cannot:

-react to messages
-edit messages after sending on some channels
-access private channels

Thanks!

**Comment by jeffreywescott** [comment]
Related: https://github.com/RocketChat/Rocket.Chat/issues/3545

**Comment by harmanTheCarMan** [comment]
Should I try to change my username on github back to previous then change to new one again?

**Comment by bundacia** [comment]
@harmanlearns, yeah, I think that should get you all fixed up, if you don't mind jumping through those hoops.

**Comment by harmanTheCarMan** [comment]
@bundacia @jeffreywescott I appreciate all of your guys' help! It works now and I believe this issue can be closed :)
