### ISSUE TITLE
`/project list -r` error

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/los#55]
### Expected vs. Actual

command: `/project list -r`
results:`Error:* There is no projectReview survey for this project and cycle`

I'd like to be able to see all projects, their members and their artifact in one consistent place. Bonus points if I can be in a team channel and just type `/project` to get a nice sidebar with said info. 
### Steps to Reproduce

_command: `/project list -r`
results:`Error:* There is no projectReview survey for this project and cycle`

TAG: @shereefb @tannerwelsh

**Comment by jeffreywescott** [comment]
This has to do with whether or not the cycle is in the right state. We'll be addressing it soon-ish(TM).

**Comment by jeffreywescott** [comment]
Reviews now stay open until 3 days since the last review.
