### ISSUE TITLE
Notify facilitators when extra support might be needed

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/los#56]
Although we're looking at learner stats every Friday with the crew, it'd be extremely helpful to avoid manually tracking whether a learner's stats are consistently declining, and instead by automatically notified when stats consistently decline.

The alert will help us know when to intervene/schedule a talk with the learner so they're aware that they need to right the ship. 

Also, we want to make sure we have enough touch points with learners prior to asking them to leave for low scores.

(moved from this Asana task: https://app.asana.com/0/62830781673321/167135882943881)

**Comment by jeffreywescott** [comment]
Now handled by the UI.
