### ISSUE TITLE
Archive project channels for completed projects

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/los#57]
### Expected vs. Actual

Expected: of the channels created specifically for project teams, only the ones for still-active projects remain listed in the left panel. All others have been archived.

Actual: channel list grows and grows... :/
### Steps to Reproduce

Look at the channel list in echo. We're only half-way through cohort 1! :) So many channels. :-l

**Comment by jeffreywescott** [comment]
Project channels are dead!
