### ISSUE TITLE
Consider weighting learning feedback differentially based on XP

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/los#58]
_from @carlabagdonas, via Asana:_

What if "learning support" evals for folks on the higher side of XP differential were weighted more strongly than those on the lower side of the differential (i.e. if i have an XP of 100 and you have an XP of 50, my learning support score for you is weighted less strongly than yours of me - it's my job as a person with higher XP to provide more learning support)

**Comment by jeffreywescott** [comment]
Handled by RXP / Review Accuracy.
