### ISSUE TITLE
how can green leaners support a professional player in their learning?

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/los#59]
### Expected vs. Actual

I have yet to feel like a green learner has supported me in their learning. So I always say "agree" / middle of the road. I feel like this is not useful feedback. It seems unreasonable to expect our current learners to support me in my learning. The knowledge delta is just too great right now. 

I'd like to feel like I am giving useful feedback and in its current form this metric, from me to green learners, doesn't seem to be useful to anyone. 
### Steps to Reproduce

1) Be a programmer for 15 years
2) Play the LOC
3) Give geen learners feedback
4) Feel guilty

CC: @carlabagdonas

**Comment by jeffreywescott** [comment]
Is this still a question, @deadlyicon, given the new way teams are being formed? If not, please close. :-)
