### ISSUE TITLE
How can a pro player stay away of relative contribution when I'm only present 10% of the overall project work time?

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/los#60]
### Expected vs. Actual

As a SEP on an average of 3-4 teams at a time; How can I give an accurate relative contribution estimate when I am only present for my team part of the time? 
### Steps to Reproduce

1) Be a programmer for 15 years
2) Play the LOC
3) Guess how much your team mates contributed based on gut
4) Feel guilty

CC: @carlabagdonas

**Comment by jeffreywescott** [comment]
Is this still a question, @deadlyicon, in light of our new project-formation strategy? If not, would you please close it? :-)

**Comment by jeffreywescott** [comment]
SEPs don't do contribution anymore. Closing.
