### ISSUE TITLE
Constantly signing into echo

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/los#62]
### Expected vs. Actual

I don't want to have to sign in every day. Can our sessions last longer?
### Steps to Reproduce
1. Use echo for more than 24 hours
2. Login via Github!

**Comment by prattsj** [comment]
Really hard to click one button? 😛

**Comment by jeffreywescott** [comment]
You only have to sign-in if your token expires, which means you haven't _used_ the system in 24 hours ... which means you probably only have to sign-in after a weekend.
