### ISSUE TITLE
Correlating ZPD for a project to player ELO & XP

### ISSUE THREAD

**Issue by needdra** [LearnersGuild/los#64]
James asked the following: Can we create a way to correlate ZPD reporting for a project to player ELO rating and XP? Such that someone looking at the project can assess project difficulty based on their XP and ELO rating relative to what the other player reported?

The idea is that learners will be better able to assess project difficulty by considering their XP and ELO rating relative to that of the reporting player.

**Comment by shereefb** [comment]
love this idea. Moving it to clubhouse.
