### ISSUE TITLE
Project review submission posts are excessive

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/los#66]
Maybe let's not do this...

---

<img width="551" alt="screen shot 2016-09-02 at 5 22 33 pm" src="https://cloud.githubusercontent.com/assets/1890882/18221430/f83a3ba2-7131-11e6-8627-27d193cf99d0.png">

---

If every player is submitting a review for every project, that's [num_players x num_projects] notifications. That's cray, and I'd be surprised to learn that anyone is finding these messages very useful, anyway. :) Definitely more noise than signal at this point.

**Comment by prattsj** [comment]
If every player is submitting reviews for every project, that's [num_players x num_projects] notifications. That's cray, and I'd be surprised to learn that anyone is finding these messages very useful, anyway. :) Definitely more noise than signal at this point.

**Comment by jeffreywescott** [comment]
We are no longer sending these to #oakland.
