### ISSUE TITLE
Make avg completeness and quality scores transparent for each cycle

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#69]
### Expected vs. Actual

Two learners were trying to understand their weekly XP gain of ~12 and ~7 XP points, respectively. We wanted to just do the math to calculate XP gain for the week: (Total Hours \* C \* Q) \* Actual Contribution, and we have all the variables except for Completeness and Quality scores. 

In this case, the players' XP gains did not make sense, based on the information we have available (they had nearly identical actual contribution and identical hours, but wildly different XP gains), which led us to want to see all the numbers involved in the equation.

Generally, learners are frustrated when stats don't behave according to their expectations, based on their understanding of what's happening. Making all the information about how stats are calculated and giving them the tools to understand the math empowers them with clearer picture of which levers they need to pull to move the numbers in the direction they want.

The proposal is to make weekly Completeness and Quality averages available to each team as soon as project reviews are done, so that they a) have all the data needed to understand their XP stat and b) get immediate feedback on the completeness and quality of their project for the week.
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
I believe this is being addressed by RXP / Review Accuracy.
