### ISSUE TITLE
CPU Pinned and Chrome Tab Locked

### ISSUE THREAD

**Issue by jrobcodes** [LearnersGuild/los#7]
### Expected vs. Actual

After voting, tab was locked and preventing input.  I noticed that the CPU was pinned at 110% for a Chrome helper process, and 59% for the main Chrome process.  Image attached showing JS output at the same time.
### Steps to Reproduce

Use echo.
### Environment and Versions

![screen shot 2016-07-01 at 11 55 08 am](https://cloud.githubusercontent.com/assets/838110/16531831/1e02b21e-3f83-11e6-87a7-a843a9a77621.png)

**Comment by jeffreywescott** [comment]
I think this was related to a Gravatar bug we have since fixed. Please reopen if you see this happen again.
