### ISSUE TITLE
Misleading "invalid invite code" errors

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/los#70]
Invite code is valid. Suspecting that the issue is actually related to mismatching github and CRM (hubspot) email addresses (see errors in server logs).

On a follow-up attempt to just log in via github, new users are able to get into echo.

To repro: unsure. try signing up with an email address that doesn't match anything in the crm.

**Comment by jeffreywescott** [comment]
I don't see anything in the server logs for this. :-(

**Comment by jeffreywescott** [comment]
I don't recall seeing this during the last cohort sign-ups. Closing.
