### ISSUE TITLE
Feature request: Echo search based on IRL names

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#71]
### Expected vs. Actual

_It's hard for me to search for specific learners if I need to send them a DM because I don't know everyone's Github handles. It would be great if I could search by a learner's IRL name, but Echo would pull up their GH handle. Low-tech / short-term fix would be to get a spreadsheet / list of github handles corresponding to IRL names._
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
This is already possible:

<img width="1278" alt="airportextra_and_item-0_and_item-0_and_item-0_and_item-0" src="https://cloud.githubusercontent.com/assets/130597/21161215/8557ed18-c13c-11e6-8d00-7d5395108984.png">
