### ISSUE TITLE
Feature request: @mention sub-groups of learners

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#72]
### Expected vs. Actual

_Sometimes I might want to alert a sub-group of learners: e.g. Pod 2's home group, or all of the July cohort learners, or just the folks on a particular team. I'd love to be able to @mention sub groups of people instead of having to write their names individually. It's kind of like an email distribution list_
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by bundacia** [comment]
@carlabagdonas, maybe this is something we can solve (or work around) with channels? We could have a separate channel for each cohort or pod. Teams already have their own channel so you can just post messages there if you want to notify a particular team.

**Comment by jeffreywescott** [comment]
Agree -- this should be handled with rooms. Closing.
