### ISSUE TITLE
Others' project reviews showing up briefly on echo Oakland channel

### ISSUE THREAD

**Issue by EthanJStark** [LearnersGuild/los#73]
### Expected vs. Actual

Expecting others' project reviews to be private and not publicly visible. 
In actuality, as another individual (Harmanlearns and some others) entered a review, it was visible in the Oakland channel for a matter of 5 seconds or so.
### Steps to Reproduce

Not easy; try having others' vote in a testing environment and observing the channel they're voting on.
### Environment and Versions

Rocket.Chat+ OSX 10.11.6

**Comment by jeffreywescott** [comment]
@EthanJStark please paste a screen shot if you see this again. What likely happened is that there was a space (' ') before the `/review` command, which made echo not treat it as a slash command. Not really fixable.

**Comment by EthanJStark** [comment]
@jeffreywescott It was the correct syntax, and it legit disappeared seconds after it was there. If I see it again, I'll try to grab it!
