### ISSUE TITLE
'Learning Support' stat on 'RETROSPECTIVE RESULTS'

### ISSUE THREAD

**Issue by Compsight** [LearnersGuild/los#74]
### Expected vs. Actual

Expecting to see technical skill percentage VS seeing Learning Support at the bottom of the RETROSPECTIVE RESULTS that are delivered to players after all team members have completed their retros.
### Steps to Reproduce

When answering the last question about technical skills of your teammate, this question gets returned as the Learning Support percentage on the RETROSPECTIVE RESULTS.

**Comment by jeffreywescott** [comment]
This should be fixed now.
