### ISSUE TITLE
Stricter full name validation for player profiles

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/los#76]
I can't tell who some people are IRL because in their profile they've entered a "full name" that doesn't match the name they go by IRL (most often it's just their game handle instead). We need either better messaging around what this value is expected to be or perhaps tighter integration with a system where we've already collected their IRL name and can use it to prepopulate the field.

**Comment by jeffreywescott** [comment]
Tracked here: https://app.clubhouse.io/learnersguild/story/2099/stricter-full-name-validation-for-player-profiles
