### ISSUE TITLE
Error messaging in retro survey UI is cray

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/los#77]
User (mikeaddossi) clicked the submit button on a retro survey page and got an unexpected error message.

Two issues:

1) survey button should have been disabled to begin with (missing client-side validation)
2) the error message should've been more helpful :)

_Screen shot_
<img width="432" alt="screen shot 2016-09-30 at 2 44 31 pm" src="https://cloud.githubusercontent.com/assets/1890882/19008020/407b2b50-871d-11e6-8207-af12e24ad84a.png">

**Comment by jeffreywescott** [comment]
Actually, in this case, we should be using a slider rather than an input field, IMO.

**Comment by prattsj** [comment]
Totally unrelated (new issue?), but sure. :)

**Comment by heyheyjp** [comment]
Fixed in https://github.com/LearnersGuild/game/pull/631.
