### ISSUE TITLE
Add qualitative feedback to quality / completeness evals

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#78]
### Expected vs. Actual

_Learners should be using project reviews as an opportunity to review code and make a thorough, thoughtful assessment of the project's completeness and quality. Let's add an open-response field to project reviews in which they have to comment on both the quality of the code itself as well as the front end / user design & experience_
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
@carlabagdonas, I wonder if it wouldn't make more sense for the comments about the code to appear in GitHub _right next to_ the code. This is how most software teams do it. Thoughts?

Also, are we expecting people to get good at user experience design? That seems like mission creep to me.

**Comment by jeffreywescott** [comment]
Prrrrrr to the rescue!
