### ISSUE TITLE
Add accountability / teeth to review completion

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#79]
### Expected vs. Actual

_Learners need to complete a minimum number of reviews per cycle, and there should be some accountability measure in place to make sure that happens_
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
RXP / Review Accuracy to the rescue!
