### ISSUE TITLE
Remove project review updates from Echo channel

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#80]
### Expected vs. Actual

_There's a lot of noise in the Oakland channel whenever a retro cycle is open because there's an update message posted every time a project gets reviewed. Can these be tracked / aggregated elsewhere (sidebar? separate channel?) or at least just not posted in the main channel._
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
Duplicate of #66.
