### ISSUE TITLE
Ensure players get a clear error message if their votes are not counted

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#81]
### Expected vs. Actual

_Some people still seem confused about whether their votes are going through / being counted. Today someone voted in the following format: /vote #45 #32 (with hashtags), so their votes didn't count, but they didn't get a clear message back indicating this. I think it said something like, "validating votes..." but they should get a clear error message / response to the effect of: "OOPS your vote was not counted. As a reminder, please use this format..."_
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
@carlabagdonas -- I cannot reproduce this:

```
/vote #3 #4
Validating the goals you voted on: #3, #4
The following goals are invalid: #3, #4
Falling back to previous vote:
- (1) laudantium ut necessitatibus [1st choice]
- (2) eum cupiditate nihil [2nd choice]
```
