### ISSUE TITLE
Add project repo from current project into original goal

### ISSUE THREAD

**Issue by harmanTheCarMan** [LearnersGuild/los#82]
### Expected vs. Actual

I want to show new peeps
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
Hi, @harmanlearns. I'm not sure I understand what this suggestion is. Can you elaborate?
