### ISSUE TITLE
Project repos in GuildCrafts org

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/los#83]
Not having a central, public place to hold project artifacts (most especially the code) puts most team members (and anyone else who might be interested in referencing artifacts later) at a disadvantage.

Currently, one team member creates a repo under their own personal account. 

Instead, the system should automatically create a repo for the project (using the unique auto-generated name) under the GuildCrafts org. This would 1) eliminate the risk that someone could - whether accidentally or intentionally - destroy the team's project artifacts and 2) give us a central place to browse & review project deliverables.

**Comment by heyheyjp** [comment]
another benefit of this: automatically setting up github notifications! 🙂

**Comment by jeffreywescott** [comment]
Tracked here: https://app.clubhouse.io/learnersguild/story/2100/project-repos-in-guildcrafts-org
