### ISSUE TITLE
scrolling in retro feedback

### ISSUE THREAD

**Issue by mKleinCreative** [LearnersGuild/los#85]
### Expected vs. Actual

Had my mouse over the ZPD question in the retro feedback survey and was trying to scroll down the page, when you do that, it scrolls through integers from -100+ to 100 
### Steps to Reproduce

Try scrolling over the number field in the retro feedback survey where it asks you what you believed your ZPD for the project was.
### Environment and Versions

ECHO

**Comment by jeffreywescott** [comment]
This has been fixed.
