### ISSUE TITLE
New Players Can Change Feedback

### ISSUE THREAD

**Issue by needdra** [LearnersGuild/los#87]
Please develop a way for newer players (say first 10wks) to adjust their feedback when they realize they've made a mistake, or scored someone lower than they meant to after discussing feedback. This process should be moderated or something - like, they need to submit the request rather than being able to change it themselves.

**Comment by jeffreywescott** [comment]
Hi, @needdra -- we have a process for this, outlined on the [README](https://github.com/LearnersGuild/los) of this repository. Basically, learners can request data changes here to change their feedback: https://github.com/LearnersGuild/los/projects/1

**Comment by needdra** [comment]
great. thanks.
