### ISSUE TITLE
cycle configuration moderator interface

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/los#88]
## The Problems
- We're trying to design a very complex algorithm with a growing and changing set of needs
- The moderator cannot easily make adjustment to the results of the algorithm
- We're not able to integrate player feedback into the current cycle configuration
## Purposed Solution

The moderator has a web interface for the cycle configuration process

After the moderator closes the current cycle and starts a new one
- The moderator can ban issues from being voted on
- The moderator can see who has voted and who hasn't
- The moderator can vote for a player
- The moderator can close voting

After the moderator closes voting
- The moderator can see the result of the algorithm 
- The moderator can make adjustments to 
  - change teams created
  - change projects of teams
  - change players positions on teams
- Each player can see their their position and is notified if/when it changes
- Players given a chance to provide feedback about their position
- The moderator can choose to integrate that feedback into the cycle configuration
- The moderator can save the cycle configuration

After the moderator saves the cycle configuration its pushed into the LOS system.
## Approach

All of this could be built as a stand alone app with minimal API integration to LOS. Or it could be built as part of LOS

Not including changes to the LOS I think I could build something that passes these specs in a week or so. Maybe two if I'm also coaching. As a stand alone app this could also be something advanced players contribute to.

**Comment by jaredatron** [comment]
@shereefb @tannerwelsh @prattsj thoughts?

**Comment by heyheyjp** [comment]
Partly being addressed by https://github.com/LearnersGuild/game/issues/475.

**Comment by tannerwelsh** [comment]
Like the approach here. @shereefb is the moderator most directly affected by this change though, so my feedback is less useful.

**Comment by jeffreywescott** [comment]
This has been _mostly_ addressed by the UI. Please break-out additional suggestions into individual stories for "user benefits" rather than one big "build a UI" issue.
