### ISSUE TITLE
Consider letting teams pick their own project names

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/los#90]
Our auto-generated names like #boiling-pademelon and #fanatical-woodpecker and #apathetic-chickadee are often more awkward/weird than cute.

Teams might like to be able to create their own (perhaps more meaningful names). The system could still enforce length, uniqueness and safety/content constraints.

**Comment by jeffreywescott** [comment]
Tracked here: https://app.clubhouse.io/learnersguild/story/2102/consider-letting-teams-pick-their-own-project-names
