### ISSUE TITLE
All learners have access to other team's git repos

### ISSUE THREAD

**Issue by jason00111** [LearnersGuild/los#92]
I'd like to be able to review other group's projects on my own time outside of the Friday afternoon review time. The problem is I don't know where the git repositories for each project are.

I can sometimes find them by looking through the oakland channel history to find the team names and then looking in the team's channel to see if anyone has linked the git repo. But often the repo is not linked. I'm guessing that echo has the repos for each project from the set-artifact command so it would be nice if learners could have access to this.

**Comment by jeffreywescott** [comment]
Related #83

**Comment by jason00111** [comment]
I discovered that this functionality already exists.

In echo, if you type `/review #team-name`, echo displays the artifact url.
