### ISSUE TITLE
Shared learner lore

### ISSUE THREAD

**Issue by salmonax** [LearnersGuild/los#94]
Specific proposals (purely speculative):

Each project has a set of lore\* issues associated with it, concepts that are frequently encountered in that project. NPM modules might have something as simple as iterating through an array, or recursion, or even currying.

Contributing to the lore affects the stats in some way, so that the system can grow. I personally know that I would love to contribute to this system if I got stats for it, even if it was just an independent lore score.

There are surveys to rate the effectiveness of the learner lore for specific learning value. (ie. ask questions like "I was able to just copy and paste from here" vs. "they used the problem in a unique way, and I had to think by analogy in order to apply it") As a lore-writer, this feedback would be awesome and rewarding.

A "core lore" is evolved for Learner's, a basic Cliff Notes that every learner is highly recommended to read or skim before getting started on any goal. These can be learner-written pieces, solid links, good ebooks.

*"Lore" would usually refer to culture's legends, fairytales, and oral history. It's just a goofy term I thought would help connote that these learner-guides are something that is being passed on from learner to learner, and might be as likely to contain war stories (ie. what was most challenging about a project) as technical information and tips.

**Comment by shereefb** [comment]
Great idea. We won't get to it for another year or so :/ Closing.
