### ISSUE TITLE
Make it easier to edit my echo profile

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#96]
### Expected vs. Actual

Trying to edit the info in my echo profile - couldn't figure out how to do it after poking around a bunch, was finally pointed to the IDM page by @prattsj, but never would have known about that otherwise. There should be an easy, frictionless way to edit the info in my profile, and ideally a way to add custom fields. 

For example, we were talking today about people having the option to add their gender pronoun(s)
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
Hey, @carlabagdonas, be sure to check out the `/profile` command, also.

**Comment by jeffreywescott** [comment]
@carlabagdonas -- did you have a chance to check out `/profile`? I'm going to close this issue for now.

Also, if you'd like PGP (or other fields) added to the profile, please file a separate issue for that and will triage / prioritize it.

Thanks!

**Comment by jeffreywescott** [comment]
See also: https://github.com/LearnersGuild/los/issues/95
