### ISSUE TITLE
Unable to login to echo through rocket chat app on mobile device

### ISSUE THREAD

**Issue by AbrahamFergie** [LearnersGuild/los#97]
### Expected vs. Actual

_What were you attempting to do? What actually happened?_
unable to get to github signin page to Login to echo.learnersguild.org server
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
failed to connect to server: abort. abort 
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_
Android OS version: 5.0.1 
Phone: LG G3 
App: Rocket Chat version 2.4.0

**Comment by jeffreywescott** [comment]
Related: https://github.com/RocketChat/Rocket.Chat/issues/5014

**Comment by jeffreywescott** [comment]
Looks like this is not just Android, but iOS as well, according to https://github.com/RocketChat/Rocket.Chat/issues/5014.

**Comment by jeffreywescott** [comment]
We just merged-in the latest version of Rocket.Chat that hopefully fixes this. According to https://github.com/RocketChat/Rocket.Chat/issues/5014 it should now work on Android. They're still waiting for Apple to approve their iOS app, so it may take a few more days. I'll leave this open until then.

**Comment by jeffreywescott** [comment]
Just tested iOS and it works again.
