### ISSUE TITLE
Add custom fields / gender pronoun field to Echo profile

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#98]
### Expected vs. Actual

_Add the option to create custom profile fields, or add a field for gender pronoun so that people can list this information in their Echo profile_
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment]
Dupe of #95
